# GoReleaser configuration for KECS
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    # Working directory is handled by builds.dir, so we can use simple commands
    - go mod tidy -C ./controlplane
    - go mod download -C ./controlplane

# Notarization will be handled as a post-archive hook
# Note: GoReleaser v2 doesn't support 'after' hooks anymore
# We'll need to handle notarization differently if needed

builds:
  - id: kecs
    main: ./cmd/controlplane
    binary: kecs
    dir: ./controlplane  # Set working directory to controlplane where go.mod exists
    env:
      - CGO_ENABLED=0  # kecs CLI doesn't need DuckDB (only controlplane in container needs it)
    tags:
      - nocli  # Build without server command to avoid DuckDB dependency
    goos:
      - darwin
      - linux
      # - windows  # Windows support can be added later
    goarch:
      - amd64
      - arm64
    # macOS specific build settings
    overrides:
      - goos: darwin
        goarch: amd64
        env:
          - CGO_ENABLED=0  # kecs CLI doesn't need DuckDB
      - goos: darwin
        goarch: arm64
        env:
          - CGO_ENABLED=0  # kecs CLI doesn't need DuckDB
      # Linux specific build settings
      # CGO_ENABLED=0 for cross-compilation from macOS
      - goos: linux
        goarch: amd64
        env:
          - CGO_ENABLED=0
      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/nandemo-ya/kecs/controlplane/internal/version.Version={{.Tag}}
      - -X github.com/nandemo-ya/kecs/controlplane/internal/version.GitCommit={{.Commit}}
      - -X github.com/nandemo-ya/kecs/controlplane/internal/version.BuildDate={{.Date}}
      - -X github.com/nandemo-ya/kecs/controlplane/internal/version.GoVersion=go1.25

archives:
  - id: kecs
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}Darwin
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE
      - docs-site/guides/getting-started.md

# macOS Code Signing (for binaries inside archives)
# Note: This signs the binaries before they're packaged into archives
signs:
  - cmd: codesign
    args:
      - "--force"
      - "--options=runtime"  # Required for notarization
      - "--sign"
      - "{{ .Env.MACOS_DEVELOPER_ID }}"  # e.g. "Developer ID Application: Name (TEAM_ID)"
      - "--timestamp"  # Required for notarization
      - "${artifact}"
    artifacts: binary
    ids:
      - kecs  # Apply to kecs build
    output: true

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Refactors'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Other changes'
      order: 999

release:
  github:
    owner: nandemo-ya
    name: kecs
  
  # Release notes configuration
  header: |
    ## KECS (Kubernetes-based ECS Compatible Service) {{.Version}}
    
    ### Installation
    
    #### Homebrew (macOS/Linux)
    ```bash
    brew tap nandemo-ya/kecs
    brew install kecs
    ```
    
    #### Direct Download
    Download the appropriate binary for your platform from the assets below.
    
    #### Docker
    ```bash
    docker pull ghcr.io/nandemo-ya/kecs:{{.Version}}
    ```
    
  footer: |
    ## Full Changelog
    **Full Changelog**: https://github.com/nandemo-ya/kecs/compare/{{.PreviousTag}}...{{.Tag}}
    
    ## Documentation
    - [Getting Started](https://github.com/nandemo-ya/kecs/blob/main/docs/getting-started.md)
    - [API Reference](https://github.com/nandemo-ya/kecs/blob/main/docs/api-reference.md)
    
  draft: false
  prerelease: auto
  mode: keep-existing
  
# Homebrew formula update
brews:
  - name: kecs
    directory: Formula
    repository:
      owner: nandemo-ya
      name: homebrew-kecs
      branch: "{{ .ProjectName }}-{{ .Version }}"
      pull_request:
        enabled: true
        base:
          owner: nandemo-ya
          name: homebrew-kecs
          branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    # Formula template
    commit_author:
      name: kecs-bot
      email: kecs-bot@nandemo-ya.github.io

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    homepage: "https://github.com/nandemo-ya/kecs"
    description: "Kubernetes-based ECS Compatible Service - Run ECS workloads on Kubernetes"
    license: "Apache-2.0"

    # Dependencies
    dependencies:
      - name: docker
        type: optional
      - name: kubectl
        type: optional

    # Installation test
    test: |
      system "#{bin}/kecs", "version"

    # Caveats for users
    caveats: |
      KECS requires a Kubernetes cluster to run workloads.
      For local development, you can use:
        - Docker Desktop with Kubernetes enabled
        - k3d: brew install k3d
        - kind: brew install kind

      Quick start:
        kecs start  # Start KECS in a container
        kecs status # Check status

      For more information:
        https://github.com/nandemo-ya/kecs

# Announce releases
announce:
  slack:
    enabled: false
  twitter:
    enabled: false
  discord:
    enabled: false