# ko configuration for KECS development
# https://ko.build/configuration/

# Default build configuration
defaultBaseImage: gcr.io/distroless/static:nonroot

# Build configurations for different components
builds:
  - id: controlplane
    dir: ./controlplane
    main: ./cmd/controlplane
    env:
      - CGO_ENABLED=0
      - GOOS=linux
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/nandemo-ya/kecs/controlplane/internal/controlplane/cmd.Version={{.Env.VERSION}}

# Override base image for controlplane (needs shell for config)
baseImageOverrides:
  github.com/nandemo-ya/kecs/controlplane/cmd/controlplane: alpine:3.19