version: '3.8'

services:
  # KECS Control Plane Service
  kecs:
    image: ghcr.io/nandemo-ya/kecs:latest
    container_name: kecs-controlplane
    environment:
      - KECS_CONTAINER_MODE=true
      - KECS_DATA_DIR=/data
      - KECS_LOG_LEVEL=info
      # Optional: Keep k3d clusters on shutdown
      # - KECS_KEEP_CLUSTERS_ON_SHUTDOWN=true
    ports:
      - "8080:8080"  # API port
      - "8081:8081"  # Admin port
    volumes:
      # Mount host directory for data persistence
      - ./kecs-data:/data
      # Mount Docker socket for k3d management
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    # Add health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Remove profiles since we only have one mode now


  # Optional: LocalStack for AWS service emulation
  localstack:
    image: localstack/localstack:latest
    container_name: kecs-localstack
    environment:
      - SERVICES=s3,dynamodb,sqs,sns,secretsmanager,ssm,iam,logs,cloudwatch
      - DEBUG=0
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
    volumes:
      - ./localstack-data:/tmp/localstack
    networks:
      - kecs-network
    restart: unless-stopped
    profiles: ["localstack"]

networks:
  kecs-network:
    name: kecs-network
    driver: bridge

volumes:
  kecs-data:
    driver: local
  localstack-data:
    driver: local