version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: kecs_test
      POSTGRES_PASSWORD: kecs_test
      POSTGRES_DB: kecs_test
    ports:
      - "5432:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kecs_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-test-data: