apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localstack-data
  namespace: kecs-system
  labels:
    app: localstack
    app.kubernetes.io/name: localstack
    app.kubernetes.io/managed-by: kecs
    app.kubernetes.io/component: localstack
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi