apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: kecs-system
  labels:
    app: localstack
    app.kubernetes.io/name: localstack
    app.kubernetes.io/managed-by: kecs
    app.kubernetes.io/component: localstack
spec:
  type: ClusterIP
  selector:
    app: localstack
  ports:
  - name: edge
    port: 4566
    targetPort: 4566
    protocol: TCP