// Code generated by cmd/codegen. DO NOT EDIT.

package api

// AgentUpdateStatus represents the AgentUpdateStatus enum type
type AgentUpdateStatus string

const (
	AgentUpdateStatusSTAGING AgentUpdateStatus = "STAGING"

	AgentUpdateStatusSTAGED AgentUpdateStatus = "STAGED"

	AgentUpdateStatusUPDATING AgentUpdateStatus = "UPDATING"

	AgentUpdateStatusUPDATED AgentUpdateStatus = "UPDATED"

	AgentUpdateStatusFAILED AgentUpdateStatus = "FAILED"

	AgentUpdateStatusPENDING AgentUpdateStatus = "PENDING"
)

// ApplicationProtocol represents the ApplicationProtocol enum type
type ApplicationProtocol string

const (
	ApplicationProtocolHTTP ApplicationProtocol = "HTTP"

	ApplicationProtocolHTTP2 ApplicationProtocol = "HTTP2"

	ApplicationProtocolGRPC ApplicationProtocol = "GRPC"
)

// AssignPublicIp represents the AssignPublicIp enum type
type AssignPublicIp string

const (
	AssignPublicIpDISABLED AssignPublicIp = "DISABLED"

	AssignPublicIpENABLED AssignPublicIp = "ENABLED"
)

// AvailabilityZoneRebalancing represents the AvailabilityZoneRebalancing enum type
type AvailabilityZoneRebalancing string

const (
	AvailabilityZoneRebalancingENABLED AvailabilityZoneRebalancing = "ENABLED"

	AvailabilityZoneRebalancingDISABLED AvailabilityZoneRebalancing = "DISABLED"
)

// CPUArchitecture represents the CPUArchitecture enum type
type CPUArchitecture string

const (
	CPUArchitectureARM64 CPUArchitecture = "ARM64"

	CPUArchitectureX86_64 CPUArchitecture = "X86_64"
)

// CapacityProviderField represents the CapacityProviderField enum type
type CapacityProviderField string

const (
	CapacityProviderFieldTAGS CapacityProviderField = "TAGS"
)

// CapacityProviderStatus represents the CapacityProviderStatus enum type
type CapacityProviderStatus string

const (
	CapacityProviderStatusACTIVE CapacityProviderStatus = "ACTIVE"

	CapacityProviderStatusINACTIVE CapacityProviderStatus = "INACTIVE"
)

// CapacityProviderUpdateStatus represents the CapacityProviderUpdateStatus enum type
type CapacityProviderUpdateStatus string

const (
	CapacityProviderUpdateStatusDELETE_FAILED CapacityProviderUpdateStatus = "DELETE_FAILED"

	CapacityProviderUpdateStatusUPDATE_IN_PROGRESS CapacityProviderUpdateStatus = "UPDATE_IN_PROGRESS"

	CapacityProviderUpdateStatusUPDATE_COMPLETE CapacityProviderUpdateStatus = "UPDATE_COMPLETE"

	CapacityProviderUpdateStatusUPDATE_FAILED CapacityProviderUpdateStatus = "UPDATE_FAILED"

	CapacityProviderUpdateStatusDELETE_IN_PROGRESS CapacityProviderUpdateStatus = "DELETE_IN_PROGRESS"

	CapacityProviderUpdateStatusDELETE_COMPLETE CapacityProviderUpdateStatus = "DELETE_COMPLETE"
)

// ClusterField represents the ClusterField enum type
type ClusterField string

const (
	ClusterFieldSTATISTICS ClusterField = "STATISTICS"

	ClusterFieldTAGS ClusterField = "TAGS"

	ClusterFieldATTACHMENTS ClusterField = "ATTACHMENTS"

	ClusterFieldCONFIGURATIONS ClusterField = "CONFIGURATIONS"

	ClusterFieldSETTINGS ClusterField = "SETTINGS"
)

// ClusterSettingName represents the ClusterSettingName enum type
type ClusterSettingName string

const (
	ClusterSettingNameCONTAINER_INSIGHTS ClusterSettingName = "CONTAINER_INSIGHTS"
)

// Compatibility represents the Compatibility enum type
type Compatibility string

const (
	CompatibilityEXTERNAL Compatibility = "EXTERNAL"

	CompatibilityEC2 Compatibility = "EC2"

	CompatibilityFARGATE Compatibility = "FARGATE"
)

// Connectivity represents the Connectivity enum type
type Connectivity string

const (
	ConnectivityCONNECTED Connectivity = "CONNECTED"

	ConnectivityDISCONNECTED Connectivity = "DISCONNECTED"
)

// ContainerCondition represents the ContainerCondition enum type
type ContainerCondition string

const (
	ContainerConditionSTART ContainerCondition = "START"

	ContainerConditionCOMPLETE ContainerCondition = "COMPLETE"

	ContainerConditionSUCCESS ContainerCondition = "SUCCESS"

	ContainerConditionHEALTHY ContainerCondition = "HEALTHY"
)

// ContainerInstanceField represents the ContainerInstanceField enum type
type ContainerInstanceField string

const (
	ContainerInstanceFieldTAGS ContainerInstanceField = "TAGS"

	ContainerInstanceFieldCONTAINER_INSTANCE_HEALTH ContainerInstanceField = "CONTAINER_INSTANCE_HEALTH"
)

// ContainerInstanceStatus represents the ContainerInstanceStatus enum type
type ContainerInstanceStatus string

const (
	ContainerInstanceStatusACTIVE ContainerInstanceStatus = "ACTIVE"

	ContainerInstanceStatusDRAINING ContainerInstanceStatus = "DRAINING"

	ContainerInstanceStatusREGISTERING ContainerInstanceStatus = "REGISTERING"

	ContainerInstanceStatusDEREGISTERING ContainerInstanceStatus = "DEREGISTERING"

	ContainerInstanceStatusREGISTRATION_FAILED ContainerInstanceStatus = "REGISTRATION_FAILED"
)

// DeploymentControllerType represents the DeploymentControllerType enum type
type DeploymentControllerType string

const (
	DeploymentControllerTypeECS DeploymentControllerType = "ECS"

	DeploymentControllerTypeCODE_DEPLOY DeploymentControllerType = "CODE_DEPLOY"

	DeploymentControllerTypeEXTERNAL DeploymentControllerType = "EXTERNAL"
)

// DeploymentRolloutState represents the DeploymentRolloutState enum type
type DeploymentRolloutState string

const (
	DeploymentRolloutStateCOMPLETED DeploymentRolloutState = "COMPLETED"

	DeploymentRolloutStateFAILED DeploymentRolloutState = "FAILED"

	DeploymentRolloutStateIN_PROGRESS DeploymentRolloutState = "IN_PROGRESS"
)

// DesiredStatus represents the DesiredStatus enum type
type DesiredStatus string

const (
	DesiredStatusRUNNING DesiredStatus = "RUNNING"

	DesiredStatusPENDING DesiredStatus = "PENDING"

	DesiredStatusSTOPPED DesiredStatus = "STOPPED"
)

// DeviceCgroupPermission represents the DeviceCgroupPermission enum type
type DeviceCgroupPermission string

const (
	DeviceCgroupPermissionREAD DeviceCgroupPermission = "READ"

	DeviceCgroupPermissionWRITE DeviceCgroupPermission = "WRITE"

	DeviceCgroupPermissionMKNOD DeviceCgroupPermission = "MKNOD"
)

// EBSResourceType represents the EBSResourceType enum type
type EBSResourceType string

const (
	EBSResourceTypeVOLUME EBSResourceType = "VOLUME"
)

// EFSAuthorizationConfigIAM represents the EFSAuthorizationConfigIAM enum type
type EFSAuthorizationConfigIAM string

const (
	EFSAuthorizationConfigIAMENABLED EFSAuthorizationConfigIAM = "ENABLED"

	EFSAuthorizationConfigIAMDISABLED EFSAuthorizationConfigIAM = "DISABLED"
)

// EFSTransitEncryption represents the EFSTransitEncryption enum type
type EFSTransitEncryption string

const (
	EFSTransitEncryptionENABLED EFSTransitEncryption = "ENABLED"

	EFSTransitEncryptionDISABLED EFSTransitEncryption = "DISABLED"
)

// EnvironmentFileType represents the EnvironmentFileType enum type
type EnvironmentFileType string

const (
	EnvironmentFileTypeS3 EnvironmentFileType = "S3"
)

// ExecuteCommandLogging represents the ExecuteCommandLogging enum type
type ExecuteCommandLogging string

const (
	ExecuteCommandLoggingNONE ExecuteCommandLogging = "NONE"

	ExecuteCommandLoggingDEFAULT ExecuteCommandLogging = "DEFAULT"

	ExecuteCommandLoggingOVERRIDE ExecuteCommandLogging = "OVERRIDE"
)

// FirelensConfigurationType represents the FirelensConfigurationType enum type
type FirelensConfigurationType string

const (
	FirelensConfigurationTypeFLUENTD FirelensConfigurationType = "FLUENTD"

	FirelensConfigurationTypeFLUENTBIT FirelensConfigurationType = "FLUENTBIT"
)

// HealthStatus represents the HealthStatus enum type
type HealthStatus string

const (
	HealthStatusHEALTHY HealthStatus = "HEALTHY"

	HealthStatusUNHEALTHY HealthStatus = "UNHEALTHY"

	HealthStatusUNKNOWN HealthStatus = "UNKNOWN"
)

// InstanceHealthCheckState represents the InstanceHealthCheckState enum type
type InstanceHealthCheckState string

const (
	InstanceHealthCheckStateOK InstanceHealthCheckState = "OK"

	InstanceHealthCheckStateIMPAIRED InstanceHealthCheckState = "IMPAIRED"

	InstanceHealthCheckStateINSUFFICIENT_DATA InstanceHealthCheckState = "INSUFFICIENT_DATA"

	InstanceHealthCheckStateINITIALIZING InstanceHealthCheckState = "INITIALIZING"
)

// InstanceHealthCheckType represents the InstanceHealthCheckType enum type
type InstanceHealthCheckType string

const (
	InstanceHealthCheckTypeCONTAINER_RUNTIME InstanceHealthCheckType = "CONTAINER_RUNTIME"
)

// IpcMode represents the IpcMode enum type
type IpcMode string

const (
	IpcModeHOST IpcMode = "HOST"

	IpcModeTASK IpcMode = "TASK"

	IpcModeNONE IpcMode = "NONE"
)

// LaunchType represents the LaunchType enum type
type LaunchType string

const (
	LaunchTypeEXTERNAL LaunchType = "EXTERNAL"

	LaunchTypeEC2 LaunchType = "EC2"

	LaunchTypeFARGATE LaunchType = "FARGATE"
)

// LogDriver represents the LogDriver enum type
type LogDriver string

const (
	LogDriverSPLUNK LogDriver = "SPLUNK"

	LogDriverAWSFIRELENS LogDriver = "AWSFIRELENS"

	LogDriverJSON_FILE LogDriver = "JSON_FILE"

	LogDriverSYSLOG LogDriver = "SYSLOG"

	LogDriverJOURNALD LogDriver = "JOURNALD"

	LogDriverGELF LogDriver = "GELF"

	LogDriverFLUENTD LogDriver = "FLUENTD"

	LogDriverAWSLOGS LogDriver = "AWSLOGS"
)

// ManagedAgentName represents the ManagedAgentName enum type
type ManagedAgentName string

const (
	ManagedAgentNameExecuteCommandAgent ManagedAgentName = "ExecuteCommandAgent"
)

// ManagedDraining represents the ManagedDraining enum type
type ManagedDraining string

const (
	ManagedDrainingDISABLED ManagedDraining = "DISABLED"

	ManagedDrainingENABLED ManagedDraining = "ENABLED"
)

// ManagedScalingStatus represents the ManagedScalingStatus enum type
type ManagedScalingStatus string

const (
	ManagedScalingStatusENABLED ManagedScalingStatus = "ENABLED"

	ManagedScalingStatusDISABLED ManagedScalingStatus = "DISABLED"
)

// ManagedTerminationProtection represents the ManagedTerminationProtection enum type
type ManagedTerminationProtection string

const (
	ManagedTerminationProtectionENABLED ManagedTerminationProtection = "ENABLED"

	ManagedTerminationProtectionDISABLED ManagedTerminationProtection = "DISABLED"
)

// NetworkMode represents the NetworkMode enum type
type NetworkMode string

const (
	NetworkModeHOST NetworkMode = "HOST"

	NetworkModeAWSVPC NetworkMode = "AWSVPC"

	NetworkModeNONE NetworkMode = "NONE"

	NetworkModeBRIDGE NetworkMode = "BRIDGE"
)

// OSFamily represents the OSFamily enum type
type OSFamily string

const (
	OSFamilyWINDOWS_SERVER_2022_CORE OSFamily = "WINDOWS_SERVER_2022_CORE"

	OSFamilyWINDOWS_SERVER_2022_FULL OSFamily = "WINDOWS_SERVER_2022_FULL"

	OSFamilyWINDOWS_SERVER_20H2_CORE OSFamily = "WINDOWS_SERVER_20H2_CORE"

	OSFamilyLINUX OSFamily = "LINUX"

	OSFamilyWINDOWS_SERVER_2019_FULL OSFamily = "WINDOWS_SERVER_2019_FULL"

	OSFamilyWINDOWS_SERVER_2019_CORE OSFamily = "WINDOWS_SERVER_2019_CORE"

	OSFamilyWINDOWS_SERVER_2016_FULL OSFamily = "WINDOWS_SERVER_2016_FULL"

	OSFamilyWINDOWS_SERVER_2004_CORE OSFamily = "WINDOWS_SERVER_2004_CORE"
)

// PidMode represents the PidMode enum type
type PidMode string

const (
	PidModeHOST PidMode = "HOST"

	PidModeTASK PidMode = "TASK"
)

// PlacementConstraintType represents the PlacementConstraintType enum type
type PlacementConstraintType string

const (
	PlacementConstraintTypeDISTINCT_INSTANCE PlacementConstraintType = "DISTINCT_INSTANCE"

	PlacementConstraintTypeMEMBER_OF PlacementConstraintType = "MEMBER_OF"
)

// PlacementStrategyType represents the PlacementStrategyType enum type
type PlacementStrategyType string

const (
	PlacementStrategyTypeRANDOM PlacementStrategyType = "RANDOM"

	PlacementStrategyTypeSPREAD PlacementStrategyType = "SPREAD"

	PlacementStrategyTypeBINPACK PlacementStrategyType = "BINPACK"
)

// PlatformDeviceType represents the PlatformDeviceType enum type
type PlatformDeviceType string

const (
	PlatformDeviceTypeGPU PlatformDeviceType = "GPU"
)

// PropagateTags represents the PropagateTags enum type
type PropagateTags string

const (
	PropagateTagsSERVICE PropagateTags = "SERVICE"

	PropagateTagsNONE PropagateTags = "NONE"

	PropagateTagsTASK_DEFINITION PropagateTags = "TASK_DEFINITION"
)

// ProxyConfigurationType represents the ProxyConfigurationType enum type
type ProxyConfigurationType string

const (
	ProxyConfigurationTypeAPPMESH ProxyConfigurationType = "APPMESH"
)

// ResourceType represents the ResourceType enum type
type ResourceType string

const (
	ResourceTypeGPU ResourceType = "GPU"

	ResourceTypeINFERENCE_ACCELERATOR ResourceType = "INFERENCE_ACCELERATOR"
)

// ScaleUnit represents the ScaleUnit enum type
type ScaleUnit string

const (
	ScaleUnitPERCENT ScaleUnit = "PERCENT"
)

// SchedulingStrategy represents the SchedulingStrategy enum type
type SchedulingStrategy string

const (
	SchedulingStrategyDAEMON SchedulingStrategy = "DAEMON"

	SchedulingStrategyREPLICA SchedulingStrategy = "REPLICA"
)

// Scope represents the Scope enum type
type Scope string

const (
	ScopeTASK Scope = "TASK"

	ScopeSHARED Scope = "SHARED"
)

// ServiceDeploymentRollbackMonitorsStatus represents the ServiceDeploymentRollbackMonitorsStatus enum type
type ServiceDeploymentRollbackMonitorsStatus string

const (
	ServiceDeploymentRollbackMonitorsStatusTRIGGERED ServiceDeploymentRollbackMonitorsStatus = "TRIGGERED"

	ServiceDeploymentRollbackMonitorsStatusMONITORING ServiceDeploymentRollbackMonitorsStatus = "MONITORING"

	ServiceDeploymentRollbackMonitorsStatusMONITORING_COMPLETE ServiceDeploymentRollbackMonitorsStatus = "MONITORING_COMPLETE"

	ServiceDeploymentRollbackMonitorsStatusDISABLED ServiceDeploymentRollbackMonitorsStatus = "DISABLED"
)

// ServiceDeploymentStatus represents the ServiceDeploymentStatus enum type
type ServiceDeploymentStatus string

const (
	ServiceDeploymentStatusSUCCESSFUL ServiceDeploymentStatus = "SUCCESSFUL"

	ServiceDeploymentStatusSTOP_REQUESTED ServiceDeploymentStatus = "STOP_REQUESTED"

	ServiceDeploymentStatusIN_PROGRESS ServiceDeploymentStatus = "IN_PROGRESS"

	ServiceDeploymentStatusROLLBACK_SUCCESSFUL ServiceDeploymentStatus = "ROLLBACK_SUCCESSFUL"

	ServiceDeploymentStatusPENDING ServiceDeploymentStatus = "PENDING"

	ServiceDeploymentStatusSTOPPED ServiceDeploymentStatus = "STOPPED"

	ServiceDeploymentStatusROLLBACK_REQUESTED ServiceDeploymentStatus = "ROLLBACK_REQUESTED"

	ServiceDeploymentStatusROLLBACK_IN_PROGRESS ServiceDeploymentStatus = "ROLLBACK_IN_PROGRESS"

	ServiceDeploymentStatusROLLBACK_FAILED ServiceDeploymentStatus = "ROLLBACK_FAILED"
)

// ServiceField represents the ServiceField enum type
type ServiceField string

const (
	ServiceFieldTAGS ServiceField = "TAGS"
)

// SettingName represents the SettingName enum type
type SettingName string

const (
	SettingNameAWSVPC_TRUNKING SettingName = "AWSVPC_TRUNKING"

	SettingNameTAG_RESOURCE_AUTHORIZATION SettingName = "TAG_RESOURCE_AUTHORIZATION"

	SettingNameFARGATE_TASK_RETIREMENT_WAIT_PERIOD SettingName = "FARGATE_TASK_RETIREMENT_WAIT_PERIOD"

	SettingNameGUARD_DUTY_ACTIVATE SettingName = "GUARD_DUTY_ACTIVATE"

	SettingNameSERVICE_LONG_ARN_FORMAT SettingName = "SERVICE_LONG_ARN_FORMAT"

	SettingNameCONTAINER_INSIGHTS SettingName = "CONTAINER_INSIGHTS"

	SettingNameFARGATE_FIPS_MODE SettingName = "FARGATE_FIPS_MODE"

	SettingNameDEFAULT_LOG_DRIVER_MODE SettingName = "DEFAULT_LOG_DRIVER_MODE"

	SettingNameTASK_LONG_ARN_FORMAT SettingName = "TASK_LONG_ARN_FORMAT"

	SettingNameCONTAINER_INSTANCE_LONG_ARN_FORMAT SettingName = "CONTAINER_INSTANCE_LONG_ARN_FORMAT"
)

// SettingType represents the SettingType enum type
type SettingType string

const (
	SettingTypeUSER SettingType = "USER"

	SettingTypeAWS_MANAGED SettingType = "AWS_MANAGED"
)

// SortOrder represents the SortOrder enum type
type SortOrder string

const (
	SortOrderASC SortOrder = "ASC"

	SortOrderDESC SortOrder = "DESC"
)

// StabilityStatus represents the StabilityStatus enum type
type StabilityStatus string

const (
	StabilityStatusSTABILIZING StabilityStatus = "STABILIZING"

	StabilityStatusSTEADY_STATE StabilityStatus = "STEADY_STATE"
)

// StopServiceDeploymentStopType represents the StopServiceDeploymentStopType enum type
type StopServiceDeploymentStopType string

const (
	StopServiceDeploymentStopTypeABORT StopServiceDeploymentStopType = "ABORT"

	StopServiceDeploymentStopTypeROLLBACK StopServiceDeploymentStopType = "ROLLBACK"
)

// TargetType represents the TargetType enum type
type TargetType string

const (
	TargetTypeCONTAINER_INSTANCE TargetType = "CONTAINER_INSTANCE"
)

// TaskDefinitionFamilyStatus represents the TaskDefinitionFamilyStatus enum type
type TaskDefinitionFamilyStatus string

const (
	TaskDefinitionFamilyStatusACTIVE TaskDefinitionFamilyStatus = "ACTIVE"

	TaskDefinitionFamilyStatusINACTIVE TaskDefinitionFamilyStatus = "INACTIVE"

	TaskDefinitionFamilyStatusALL TaskDefinitionFamilyStatus = "ALL"
)

// TaskDefinitionField represents the TaskDefinitionField enum type
type TaskDefinitionField string

const (
	TaskDefinitionFieldTAGS TaskDefinitionField = "TAGS"
)

// TaskDefinitionPlacementConstraintType represents the TaskDefinitionPlacementConstraintType enum type
type TaskDefinitionPlacementConstraintType string

const (
	TaskDefinitionPlacementConstraintTypeMEMBER_OF TaskDefinitionPlacementConstraintType = "MEMBER_OF"
)

// TaskDefinitionStatus represents the TaskDefinitionStatus enum type
type TaskDefinitionStatus string

const (
	TaskDefinitionStatusACTIVE TaskDefinitionStatus = "ACTIVE"

	TaskDefinitionStatusINACTIVE TaskDefinitionStatus = "INACTIVE"

	TaskDefinitionStatusDELETE_IN_PROGRESS TaskDefinitionStatus = "DELETE_IN_PROGRESS"
)

// TaskField represents the TaskField enum type
type TaskField string

const (
	TaskFieldTAGS TaskField = "TAGS"
)

// TaskFilesystemType represents the TaskFilesystemType enum type
type TaskFilesystemType string

const (
	TaskFilesystemTypeXFS TaskFilesystemType = "XFS"

	TaskFilesystemTypeNTFS TaskFilesystemType = "NTFS"

	TaskFilesystemTypeEXT3 TaskFilesystemType = "EXT3"

	TaskFilesystemTypeEXT4 TaskFilesystemType = "EXT4"
)

// TaskSetField represents the TaskSetField enum type
type TaskSetField string

const (
	TaskSetFieldTAGS TaskSetField = "TAGS"
)

// TaskStopCode represents the TaskStopCode enum type
type TaskStopCode string

const (
	TaskStopCodeUSER_INITIATED TaskStopCode = "USER_INITIATED"

	TaskStopCodeSERVICE_SCHEDULER_INITIATED TaskStopCode = "SERVICE_SCHEDULER_INITIATED"

	TaskStopCodeSPOT_INTERRUPTION TaskStopCode = "SPOT_INTERRUPTION"

	TaskStopCodeTERMINATION_NOTICE TaskStopCode = "TERMINATION_NOTICE"

	TaskStopCodeTASK_FAILED_TO_START TaskStopCode = "TASK_FAILED_TO_START"

	TaskStopCodeESSENTIAL_CONTAINER_EXITED TaskStopCode = "ESSENTIAL_CONTAINER_EXITED"
)

// TransportProtocol represents the TransportProtocol enum type
type TransportProtocol string

const (
	TransportProtocolTCP TransportProtocol = "TCP"

	TransportProtocolUDP TransportProtocol = "UDP"
)

// UlimitName represents the UlimitName enum type
type UlimitName string

const (
	UlimitNameCORE UlimitName = "CORE"

	UlimitNameNOFILE UlimitName = "NOFILE"

	UlimitNameRSS UlimitName = "RSS"

	UlimitNameSIGPENDING UlimitName = "SIGPENDING"

	UlimitNameNICE UlimitName = "NICE"

	UlimitNameNPROC UlimitName = "NPROC"

	UlimitNameRTPRIO UlimitName = "RTPRIO"

	UlimitNameRTTIME UlimitName = "RTTIME"

	UlimitNameSTACK UlimitName = "STACK"

	UlimitNameMEMLOCK UlimitName = "MEMLOCK"

	UlimitNameMSGQUEUE UlimitName = "MSGQUEUE"

	UlimitNameCPU UlimitName = "CPU"

	UlimitNameDATA UlimitName = "DATA"

	UlimitNameFSIZE UlimitName = "FSIZE"

	UlimitNameLOCKS UlimitName = "LOCKS"
)

// VersionConsistency represents the VersionConsistency enum type
type VersionConsistency string

const (
	VersionConsistencyENABLED VersionConsistency = "ENABLED"

	VersionConsistencyDISABLED VersionConsistency = "DISABLED"
)
