// Code generated by cmd/codegen. DO NOT EDIT.

package api

import (
	"context"
)

// AmazonEC2ContainerServiceV20141113API defines the interface for ecs operations
type AmazonEC2ContainerServiceV20141113API interface {

	// CreateCapacityProvider performs the CreateCapacityProvider operation
	CreateCapacityProvider(ctx context.Context, input *CreateCapacityProviderRequest) (*CreateCapacityProviderResponse, error)

	// CreateCluster performs the CreateCluster operation
	CreateCluster(ctx context.Context, input *CreateClusterRequest) (*CreateClusterResponse, error)

	// CreateService performs the CreateService operation
	CreateService(ctx context.Context, input *CreateServiceRequest) (*CreateServiceResponse, error)

	// CreateTaskSet performs the CreateTaskSet operation
	CreateTaskSet(ctx context.Context, input *CreateTaskSetRequest) (*CreateTaskSetResponse, error)

	// DeleteAccountSetting performs the DeleteAccountSetting operation
	DeleteAccountSetting(ctx context.Context, input *DeleteAccountSettingRequest) (*DeleteAccountSettingResponse, error)

	// DeleteAttributes performs the DeleteAttributes operation
	DeleteAttributes(ctx context.Context, input *DeleteAttributesRequest) (*DeleteAttributesResponse, error)

	// DeleteCapacityProvider performs the DeleteCapacityProvider operation
	DeleteCapacityProvider(ctx context.Context, input *DeleteCapacityProviderRequest) (*DeleteCapacityProviderResponse, error)

	// DeleteCluster performs the DeleteCluster operation
	DeleteCluster(ctx context.Context, input *DeleteClusterRequest) (*DeleteClusterResponse, error)

	// DeleteService performs the DeleteService operation
	DeleteService(ctx context.Context, input *DeleteServiceRequest) (*DeleteServiceResponse, error)

	// DeleteTaskDefinitions performs the DeleteTaskDefinitions operation
	DeleteTaskDefinitions(ctx context.Context, input *DeleteTaskDefinitionsRequest) (*DeleteTaskDefinitionsResponse, error)

	// DeleteTaskSet performs the DeleteTaskSet operation
	DeleteTaskSet(ctx context.Context, input *DeleteTaskSetRequest) (*DeleteTaskSetResponse, error)

	// DeregisterContainerInstance performs the DeregisterContainerInstance operation
	DeregisterContainerInstance(ctx context.Context, input *DeregisterContainerInstanceRequest) (*DeregisterContainerInstanceResponse, error)

	// DeregisterTaskDefinition performs the DeregisterTaskDefinition operation
	DeregisterTaskDefinition(ctx context.Context, input *DeregisterTaskDefinitionRequest) (*DeregisterTaskDefinitionResponse, error)

	// DescribeCapacityProviders performs the DescribeCapacityProviders operation
	DescribeCapacityProviders(ctx context.Context, input *DescribeCapacityProvidersRequest) (*DescribeCapacityProvidersResponse, error)

	// DescribeClusters performs the DescribeClusters operation
	DescribeClusters(ctx context.Context, input *DescribeClustersRequest) (*DescribeClustersResponse, error)

	// DescribeContainerInstances performs the DescribeContainerInstances operation
	DescribeContainerInstances(ctx context.Context, input *DescribeContainerInstancesRequest) (*DescribeContainerInstancesResponse, error)

	// DescribeServiceDeployments performs the DescribeServiceDeployments operation
	DescribeServiceDeployments(ctx context.Context, input *DescribeServiceDeploymentsRequest) (*DescribeServiceDeploymentsResponse, error)

	// DescribeServiceRevisions performs the DescribeServiceRevisions operation
	DescribeServiceRevisions(ctx context.Context, input *DescribeServiceRevisionsRequest) (*DescribeServiceRevisionsResponse, error)

	// DescribeServices performs the DescribeServices operation
	DescribeServices(ctx context.Context, input *DescribeServicesRequest) (*DescribeServicesResponse, error)

	// DescribeTaskDefinition performs the DescribeTaskDefinition operation
	DescribeTaskDefinition(ctx context.Context, input *DescribeTaskDefinitionRequest) (*DescribeTaskDefinitionResponse, error)

	// DescribeTaskSets performs the DescribeTaskSets operation
	DescribeTaskSets(ctx context.Context, input *DescribeTaskSetsRequest) (*DescribeTaskSetsResponse, error)

	// DescribeTasks performs the DescribeTasks operation
	DescribeTasks(ctx context.Context, input *DescribeTasksRequest) (*DescribeTasksResponse, error)

	// DiscoverPollEndpoint performs the DiscoverPollEndpoint operation
	DiscoverPollEndpoint(ctx context.Context, input *DiscoverPollEndpointRequest) (*DiscoverPollEndpointResponse, error)

	// ExecuteCommand performs the ExecuteCommand operation
	ExecuteCommand(ctx context.Context, input *ExecuteCommandRequest) (*ExecuteCommandResponse, error)

	// GetTaskProtection performs the GetTaskProtection operation
	GetTaskProtection(ctx context.Context, input *GetTaskProtectionRequest) (*GetTaskProtectionResponse, error)

	// ListAccountSettings performs the ListAccountSettings operation
	ListAccountSettings(ctx context.Context, input *ListAccountSettingsRequest) (*ListAccountSettingsResponse, error)

	// ListAttributes performs the ListAttributes operation
	ListAttributes(ctx context.Context, input *ListAttributesRequest) (*ListAttributesResponse, error)

	// ListClusters performs the ListClusters operation
	ListClusters(ctx context.Context, input *ListClustersRequest) (*ListClustersResponse, error)

	// ListContainerInstances performs the ListContainerInstances operation
	ListContainerInstances(ctx context.Context, input *ListContainerInstancesRequest) (*ListContainerInstancesResponse, error)

	// ListServiceDeployments performs the ListServiceDeployments operation
	ListServiceDeployments(ctx context.Context, input *ListServiceDeploymentsRequest) (*ListServiceDeploymentsResponse, error)

	// ListServices performs the ListServices operation
	ListServices(ctx context.Context, input *ListServicesRequest) (*ListServicesResponse, error)

	// ListServicesByNamespace performs the ListServicesByNamespace operation
	ListServicesByNamespace(ctx context.Context, input *ListServicesByNamespaceRequest) (*ListServicesByNamespaceResponse, error)

	// ListTagsForResource performs the ListTagsForResource operation
	ListTagsForResource(ctx context.Context, input *ListTagsForResourceRequest) (*ListTagsForResourceResponse, error)

	// ListTaskDefinitionFamilies performs the ListTaskDefinitionFamilies operation
	ListTaskDefinitionFamilies(ctx context.Context, input *ListTaskDefinitionFamiliesRequest) (*ListTaskDefinitionFamiliesResponse, error)

	// ListTaskDefinitions performs the ListTaskDefinitions operation
	ListTaskDefinitions(ctx context.Context, input *ListTaskDefinitionsRequest) (*ListTaskDefinitionsResponse, error)

	// ListTasks performs the ListTasks operation
	ListTasks(ctx context.Context, input *ListTasksRequest) (*ListTasksResponse, error)

	// PutAccountSetting performs the PutAccountSetting operation
	PutAccountSetting(ctx context.Context, input *PutAccountSettingRequest) (*PutAccountSettingResponse, error)

	// PutAccountSettingDefault performs the PutAccountSettingDefault operation
	PutAccountSettingDefault(ctx context.Context, input *PutAccountSettingDefaultRequest) (*PutAccountSettingDefaultResponse, error)

	// PutAttributes performs the PutAttributes operation
	PutAttributes(ctx context.Context, input *PutAttributesRequest) (*PutAttributesResponse, error)

	// PutClusterCapacityProviders performs the PutClusterCapacityProviders operation
	PutClusterCapacityProviders(ctx context.Context, input *PutClusterCapacityProvidersRequest) (*PutClusterCapacityProvidersResponse, error)

	// RegisterContainerInstance performs the RegisterContainerInstance operation
	RegisterContainerInstance(ctx context.Context, input *RegisterContainerInstanceRequest) (*RegisterContainerInstanceResponse, error)

	// RegisterTaskDefinition performs the RegisterTaskDefinition operation
	RegisterTaskDefinition(ctx context.Context, input *RegisterTaskDefinitionRequest) (*RegisterTaskDefinitionResponse, error)

	// RunTask performs the RunTask operation
	RunTask(ctx context.Context, input *RunTaskRequest) (*RunTaskResponse, error)

	// StartTask performs the StartTask operation
	StartTask(ctx context.Context, input *StartTaskRequest) (*StartTaskResponse, error)

	// StopServiceDeployment performs the StopServiceDeployment operation
	StopServiceDeployment(ctx context.Context, input *StopServiceDeploymentRequest) (*StopServiceDeploymentResponse, error)

	// StopTask performs the StopTask operation
	StopTask(ctx context.Context, input *StopTaskRequest) (*StopTaskResponse, error)

	// SubmitAttachmentStateChanges performs the SubmitAttachmentStateChanges operation
	SubmitAttachmentStateChanges(ctx context.Context, input *SubmitAttachmentStateChangesRequest) (*SubmitAttachmentStateChangesResponse, error)

	// SubmitContainerStateChange performs the SubmitContainerStateChange operation
	SubmitContainerStateChange(ctx context.Context, input *SubmitContainerStateChangeRequest) (*SubmitContainerStateChangeResponse, error)

	// SubmitTaskStateChange performs the SubmitTaskStateChange operation
	SubmitTaskStateChange(ctx context.Context, input *SubmitTaskStateChangeRequest) (*SubmitTaskStateChangeResponse, error)

	// TagResource performs the TagResource operation
	TagResource(ctx context.Context, input *TagResourceRequest) (*TagResourceResponse, error)

	// UntagResource performs the UntagResource operation
	UntagResource(ctx context.Context, input *UntagResourceRequest) (*UntagResourceResponse, error)

	// UpdateCapacityProvider performs the UpdateCapacityProvider operation
	UpdateCapacityProvider(ctx context.Context, input *UpdateCapacityProviderRequest) (*UpdateCapacityProviderResponse, error)

	// UpdateCluster performs the UpdateCluster operation
	UpdateCluster(ctx context.Context, input *UpdateClusterRequest) (*UpdateClusterResponse, error)

	// UpdateClusterSettings performs the UpdateClusterSettings operation
	UpdateClusterSettings(ctx context.Context, input *UpdateClusterSettingsRequest) (*UpdateClusterSettingsResponse, error)

	// UpdateContainerAgent performs the UpdateContainerAgent operation
	UpdateContainerAgent(ctx context.Context, input *UpdateContainerAgentRequest) (*UpdateContainerAgentResponse, error)

	// UpdateContainerInstancesState performs the UpdateContainerInstancesState operation
	UpdateContainerInstancesState(ctx context.Context, input *UpdateContainerInstancesStateRequest) (*UpdateContainerInstancesStateResponse, error)

	// UpdateService performs the UpdateService operation
	UpdateService(ctx context.Context, input *UpdateServiceRequest) (*UpdateServiceResponse, error)

	// UpdateServicePrimaryTaskSet performs the UpdateServicePrimaryTaskSet operation
	UpdateServicePrimaryTaskSet(ctx context.Context, input *UpdateServicePrimaryTaskSetRequest) (*UpdateServicePrimaryTaskSetResponse, error)

	// UpdateTaskProtection performs the UpdateTaskProtection operation
	UpdateTaskProtection(ctx context.Context, input *UpdateTaskProtectionRequest) (*UpdateTaskProtectionResponse, error)

	// UpdateTaskSet performs the UpdateTaskSet operation
	UpdateTaskSet(ctx context.Context, input *UpdateTaskSetRequest) (*UpdateTaskSetResponse, error)
}

// Operation names
const (
	OperationCreateCapacityProvider = "CreateCapacityProvider"

	OperationCreateCluster = "CreateCluster"

	OperationCreateService = "CreateService"

	OperationCreateTaskSet = "CreateTaskSet"

	OperationDeleteAccountSetting = "DeleteAccountSetting"

	OperationDeleteAttributes = "DeleteAttributes"

	OperationDeleteCapacityProvider = "DeleteCapacityProvider"

	OperationDeleteCluster = "DeleteCluster"

	OperationDeleteService = "DeleteService"

	OperationDeleteTaskDefinitions = "DeleteTaskDefinitions"

	OperationDeleteTaskSet = "DeleteTaskSet"

	OperationDeregisterContainerInstance = "DeregisterContainerInstance"

	OperationDeregisterTaskDefinition = "DeregisterTaskDefinition"

	OperationDescribeCapacityProviders = "DescribeCapacityProviders"

	OperationDescribeClusters = "DescribeClusters"

	OperationDescribeContainerInstances = "DescribeContainerInstances"

	OperationDescribeServiceDeployments = "DescribeServiceDeployments"

	OperationDescribeServiceRevisions = "DescribeServiceRevisions"

	OperationDescribeServices = "DescribeServices"

	OperationDescribeTaskDefinition = "DescribeTaskDefinition"

	OperationDescribeTaskSets = "DescribeTaskSets"

	OperationDescribeTasks = "DescribeTasks"

	OperationDiscoverPollEndpoint = "DiscoverPollEndpoint"

	OperationExecuteCommand = "ExecuteCommand"

	OperationGetTaskProtection = "GetTaskProtection"

	OperationListAccountSettings = "ListAccountSettings"

	OperationListAttributes = "ListAttributes"

	OperationListClusters = "ListClusters"

	OperationListContainerInstances = "ListContainerInstances"

	OperationListServiceDeployments = "ListServiceDeployments"

	OperationListServices = "ListServices"

	OperationListServicesByNamespace = "ListServicesByNamespace"

	OperationListTagsForResource = "ListTagsForResource"

	OperationListTaskDefinitionFamilies = "ListTaskDefinitionFamilies"

	OperationListTaskDefinitions = "ListTaskDefinitions"

	OperationListTasks = "ListTasks"

	OperationPutAccountSetting = "PutAccountSetting"

	OperationPutAccountSettingDefault = "PutAccountSettingDefault"

	OperationPutAttributes = "PutAttributes"

	OperationPutClusterCapacityProviders = "PutClusterCapacityProviders"

	OperationRegisterContainerInstance = "RegisterContainerInstance"

	OperationRegisterTaskDefinition = "RegisterTaskDefinition"

	OperationRunTask = "RunTask"

	OperationStartTask = "StartTask"

	OperationStopServiceDeployment = "StopServiceDeployment"

	OperationStopTask = "StopTask"

	OperationSubmitAttachmentStateChanges = "SubmitAttachmentStateChanges"

	OperationSubmitContainerStateChange = "SubmitContainerStateChange"

	OperationSubmitTaskStateChange = "SubmitTaskStateChange"

	OperationTagResource = "TagResource"

	OperationUntagResource = "UntagResource"

	OperationUpdateCapacityProvider = "UpdateCapacityProvider"

	OperationUpdateCluster = "UpdateCluster"

	OperationUpdateClusterSettings = "UpdateClusterSettings"

	OperationUpdateContainerAgent = "UpdateContainerAgent"

	OperationUpdateContainerInstancesState = "UpdateContainerInstancesState"

	OperationUpdateService = "UpdateService"

	OperationUpdateServicePrimaryTaskSet = "UpdateServicePrimaryTaskSet"

	OperationUpdateTaskProtection = "UpdateTaskProtection"

	OperationUpdateTaskSet = "UpdateTaskSet"
)

// Error types
var (

	// ClientException is returned by CreateCapacityProvider
	_ = &ClientException{}

	// InvalidParameterException is returned by CreateCapacityProvider
	_ = &InvalidParameterException{}

	// LimitExceededException is returned by CreateCapacityProvider
	_ = &LimitExceededException{}

	// ServerException is returned by CreateCapacityProvider
	_ = &ServerException{}

	// UpdateInProgressException is returned by CreateCapacityProvider
	_ = &UpdateInProgressException{}

	// ClientException is returned by CreateCluster
	_ = &ClientException{}

	// InvalidParameterException is returned by CreateCluster
	_ = &InvalidParameterException{}

	// NamespaceNotFoundException is returned by CreateCluster
	_ = &NamespaceNotFoundException{}

	// ServerException is returned by CreateCluster
	_ = &ServerException{}

	// AccessDeniedException is returned by CreateService
	_ = &AccessDeniedException{}

	// ClientException is returned by CreateService
	_ = &ClientException{}

	// ClusterNotFoundException is returned by CreateService
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by CreateService
	_ = &InvalidParameterException{}

	// NamespaceNotFoundException is returned by CreateService
	_ = &NamespaceNotFoundException{}

	// PlatformTaskDefinitionIncompatibilityException is returned by CreateService
	_ = &PlatformTaskDefinitionIncompatibilityException{}

	// PlatformUnknownException is returned by CreateService
	_ = &PlatformUnknownException{}

	// ServerException is returned by CreateService
	_ = &ServerException{}

	// UnsupportedFeatureException is returned by CreateService
	_ = &UnsupportedFeatureException{}

	// AccessDeniedException is returned by CreateTaskSet
	_ = &AccessDeniedException{}

	// ClientException is returned by CreateTaskSet
	_ = &ClientException{}

	// ClusterNotFoundException is returned by CreateTaskSet
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by CreateTaskSet
	_ = &InvalidParameterException{}

	// NamespaceNotFoundException is returned by CreateTaskSet
	_ = &NamespaceNotFoundException{}

	// PlatformTaskDefinitionIncompatibilityException is returned by CreateTaskSet
	_ = &PlatformTaskDefinitionIncompatibilityException{}

	// PlatformUnknownException is returned by CreateTaskSet
	_ = &PlatformUnknownException{}

	// ServerException is returned by CreateTaskSet
	_ = &ServerException{}

	// ServiceNotActiveException is returned by CreateTaskSet
	_ = &ServiceNotActiveException{}

	// ServiceNotFoundException is returned by CreateTaskSet
	_ = &ServiceNotFoundException{}

	// UnsupportedFeatureException is returned by CreateTaskSet
	_ = &UnsupportedFeatureException{}

	// ClientException is returned by DeleteAccountSetting
	_ = &ClientException{}

	// InvalidParameterException is returned by DeleteAccountSetting
	_ = &InvalidParameterException{}

	// ServerException is returned by DeleteAccountSetting
	_ = &ServerException{}

	// ClusterNotFoundException is returned by DeleteAttributes
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by DeleteAttributes
	_ = &InvalidParameterException{}

	// TargetNotFoundException is returned by DeleteAttributes
	_ = &TargetNotFoundException{}

	// ClientException is returned by DeleteCapacityProvider
	_ = &ClientException{}

	// InvalidParameterException is returned by DeleteCapacityProvider
	_ = &InvalidParameterException{}

	// ServerException is returned by DeleteCapacityProvider
	_ = &ServerException{}

	// ClientException is returned by DeleteCluster
	_ = &ClientException{}

	// ClusterContainsContainerInstancesException is returned by DeleteCluster
	_ = &ClusterContainsContainerInstancesException{}

	// ClusterContainsServicesException is returned by DeleteCluster
	_ = &ClusterContainsServicesException{}

	// ClusterContainsTasksException is returned by DeleteCluster
	_ = &ClusterContainsTasksException{}

	// ClusterNotFoundException is returned by DeleteCluster
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by DeleteCluster
	_ = &InvalidParameterException{}

	// ServerException is returned by DeleteCluster
	_ = &ServerException{}

	// UpdateInProgressException is returned by DeleteCluster
	_ = &UpdateInProgressException{}

	// ClientException is returned by DeleteService
	_ = &ClientException{}

	// ClusterNotFoundException is returned by DeleteService
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by DeleteService
	_ = &InvalidParameterException{}

	// ServerException is returned by DeleteService
	_ = &ServerException{}

	// ServiceNotFoundException is returned by DeleteService
	_ = &ServiceNotFoundException{}

	// AccessDeniedException is returned by DeleteTaskDefinitions
	_ = &AccessDeniedException{}

	// ClientException is returned by DeleteTaskDefinitions
	_ = &ClientException{}

	// InvalidParameterException is returned by DeleteTaskDefinitions
	_ = &InvalidParameterException{}

	// ServerException is returned by DeleteTaskDefinitions
	_ = &ServerException{}

	// AccessDeniedException is returned by DeleteTaskSet
	_ = &AccessDeniedException{}

	// ClientException is returned by DeleteTaskSet
	_ = &ClientException{}

	// ClusterNotFoundException is returned by DeleteTaskSet
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by DeleteTaskSet
	_ = &InvalidParameterException{}

	// ServerException is returned by DeleteTaskSet
	_ = &ServerException{}

	// ServiceNotActiveException is returned by DeleteTaskSet
	_ = &ServiceNotActiveException{}

	// ServiceNotFoundException is returned by DeleteTaskSet
	_ = &ServiceNotFoundException{}

	// TaskSetNotFoundException is returned by DeleteTaskSet
	_ = &TaskSetNotFoundException{}

	// UnsupportedFeatureException is returned by DeleteTaskSet
	_ = &UnsupportedFeatureException{}

	// ClientException is returned by DeregisterContainerInstance
	_ = &ClientException{}

	// ClusterNotFoundException is returned by DeregisterContainerInstance
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by DeregisterContainerInstance
	_ = &InvalidParameterException{}

	// ServerException is returned by DeregisterContainerInstance
	_ = &ServerException{}

	// ClientException is returned by DeregisterTaskDefinition
	_ = &ClientException{}

	// InvalidParameterException is returned by DeregisterTaskDefinition
	_ = &InvalidParameterException{}

	// ServerException is returned by DeregisterTaskDefinition
	_ = &ServerException{}

	// ClientException is returned by DescribeCapacityProviders
	_ = &ClientException{}

	// InvalidParameterException is returned by DescribeCapacityProviders
	_ = &InvalidParameterException{}

	// ServerException is returned by DescribeCapacityProviders
	_ = &ServerException{}

	// ClientException is returned by DescribeClusters
	_ = &ClientException{}

	// InvalidParameterException is returned by DescribeClusters
	_ = &InvalidParameterException{}

	// ServerException is returned by DescribeClusters
	_ = &ServerException{}

	// ClientException is returned by DescribeContainerInstances
	_ = &ClientException{}

	// ClusterNotFoundException is returned by DescribeContainerInstances
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by DescribeContainerInstances
	_ = &InvalidParameterException{}

	// ServerException is returned by DescribeContainerInstances
	_ = &ServerException{}

	// AccessDeniedException is returned by DescribeServiceDeployments
	_ = &AccessDeniedException{}

	// ClientException is returned by DescribeServiceDeployments
	_ = &ClientException{}

	// ClusterNotFoundException is returned by DescribeServiceDeployments
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by DescribeServiceDeployments
	_ = &InvalidParameterException{}

	// ServerException is returned by DescribeServiceDeployments
	_ = &ServerException{}

	// ServiceNotFoundException is returned by DescribeServiceDeployments
	_ = &ServiceNotFoundException{}

	// UnsupportedFeatureException is returned by DescribeServiceDeployments
	_ = &UnsupportedFeatureException{}

	// AccessDeniedException is returned by DescribeServiceRevisions
	_ = &AccessDeniedException{}

	// ClientException is returned by DescribeServiceRevisions
	_ = &ClientException{}

	// ClusterNotFoundException is returned by DescribeServiceRevisions
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by DescribeServiceRevisions
	_ = &InvalidParameterException{}

	// ServerException is returned by DescribeServiceRevisions
	_ = &ServerException{}

	// ServiceNotFoundException is returned by DescribeServiceRevisions
	_ = &ServiceNotFoundException{}

	// UnsupportedFeatureException is returned by DescribeServiceRevisions
	_ = &UnsupportedFeatureException{}

	// ClientException is returned by DescribeServices
	_ = &ClientException{}

	// ClusterNotFoundException is returned by DescribeServices
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by DescribeServices
	_ = &InvalidParameterException{}

	// ServerException is returned by DescribeServices
	_ = &ServerException{}

	// ClientException is returned by DescribeTaskDefinition
	_ = &ClientException{}

	// InvalidParameterException is returned by DescribeTaskDefinition
	_ = &InvalidParameterException{}

	// ServerException is returned by DescribeTaskDefinition
	_ = &ServerException{}

	// AccessDeniedException is returned by DescribeTaskSets
	_ = &AccessDeniedException{}

	// ClientException is returned by DescribeTaskSets
	_ = &ClientException{}

	// ClusterNotFoundException is returned by DescribeTaskSets
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by DescribeTaskSets
	_ = &InvalidParameterException{}

	// ServerException is returned by DescribeTaskSets
	_ = &ServerException{}

	// ServiceNotActiveException is returned by DescribeTaskSets
	_ = &ServiceNotActiveException{}

	// ServiceNotFoundException is returned by DescribeTaskSets
	_ = &ServiceNotFoundException{}

	// UnsupportedFeatureException is returned by DescribeTaskSets
	_ = &UnsupportedFeatureException{}

	// ClientException is returned by DescribeTasks
	_ = &ClientException{}

	// ClusterNotFoundException is returned by DescribeTasks
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by DescribeTasks
	_ = &InvalidParameterException{}

	// ServerException is returned by DescribeTasks
	_ = &ServerException{}

	// ClientException is returned by DiscoverPollEndpoint
	_ = &ClientException{}

	// ServerException is returned by DiscoverPollEndpoint
	_ = &ServerException{}

	// AccessDeniedException is returned by ExecuteCommand
	_ = &AccessDeniedException{}

	// ClientException is returned by ExecuteCommand
	_ = &ClientException{}

	// ClusterNotFoundException is returned by ExecuteCommand
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by ExecuteCommand
	_ = &InvalidParameterException{}

	// ServerException is returned by ExecuteCommand
	_ = &ServerException{}

	// TargetNotConnectedException is returned by ExecuteCommand
	_ = &TargetNotConnectedException{}

	// AccessDeniedException is returned by GetTaskProtection
	_ = &AccessDeniedException{}

	// ClientException is returned by GetTaskProtection
	_ = &ClientException{}

	// ClusterNotFoundException is returned by GetTaskProtection
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by GetTaskProtection
	_ = &InvalidParameterException{}

	// ResourceNotFoundException is returned by GetTaskProtection
	_ = &ResourceNotFoundException{}

	// ServerException is returned by GetTaskProtection
	_ = &ServerException{}

	// UnsupportedFeatureException is returned by GetTaskProtection
	_ = &UnsupportedFeatureException{}

	// ClientException is returned by ListAccountSettings
	_ = &ClientException{}

	// InvalidParameterException is returned by ListAccountSettings
	_ = &InvalidParameterException{}

	// ServerException is returned by ListAccountSettings
	_ = &ServerException{}

	// ClusterNotFoundException is returned by ListAttributes
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by ListAttributes
	_ = &InvalidParameterException{}

	// ClientException is returned by ListClusters
	_ = &ClientException{}

	// InvalidParameterException is returned by ListClusters
	_ = &InvalidParameterException{}

	// ServerException is returned by ListClusters
	_ = &ServerException{}

	// ClientException is returned by ListContainerInstances
	_ = &ClientException{}

	// ClusterNotFoundException is returned by ListContainerInstances
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by ListContainerInstances
	_ = &InvalidParameterException{}

	// ServerException is returned by ListContainerInstances
	_ = &ServerException{}

	// AccessDeniedException is returned by ListServiceDeployments
	_ = &AccessDeniedException{}

	// ClientException is returned by ListServiceDeployments
	_ = &ClientException{}

	// InvalidParameterException is returned by ListServiceDeployments
	_ = &InvalidParameterException{}

	// ServerException is returned by ListServiceDeployments
	_ = &ServerException{}

	// ServiceNotFoundException is returned by ListServiceDeployments
	_ = &ServiceNotFoundException{}

	// UnsupportedFeatureException is returned by ListServiceDeployments
	_ = &UnsupportedFeatureException{}

	// ClientException is returned by ListServices
	_ = &ClientException{}

	// ClusterNotFoundException is returned by ListServices
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by ListServices
	_ = &InvalidParameterException{}

	// ServerException is returned by ListServices
	_ = &ServerException{}

	// ClientException is returned by ListServicesByNamespace
	_ = &ClientException{}

	// InvalidParameterException is returned by ListServicesByNamespace
	_ = &InvalidParameterException{}

	// NamespaceNotFoundException is returned by ListServicesByNamespace
	_ = &NamespaceNotFoundException{}

	// ServerException is returned by ListServicesByNamespace
	_ = &ServerException{}

	// ClientException is returned by ListTagsForResource
	_ = &ClientException{}

	// ClusterNotFoundException is returned by ListTagsForResource
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by ListTagsForResource
	_ = &InvalidParameterException{}

	// ServerException is returned by ListTagsForResource
	_ = &ServerException{}

	// ClientException is returned by ListTaskDefinitionFamilies
	_ = &ClientException{}

	// InvalidParameterException is returned by ListTaskDefinitionFamilies
	_ = &InvalidParameterException{}

	// ServerException is returned by ListTaskDefinitionFamilies
	_ = &ServerException{}

	// ClientException is returned by ListTaskDefinitions
	_ = &ClientException{}

	// InvalidParameterException is returned by ListTaskDefinitions
	_ = &InvalidParameterException{}

	// ServerException is returned by ListTaskDefinitions
	_ = &ServerException{}

	// ClientException is returned by ListTasks
	_ = &ClientException{}

	// ClusterNotFoundException is returned by ListTasks
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by ListTasks
	_ = &InvalidParameterException{}

	// ServerException is returned by ListTasks
	_ = &ServerException{}

	// ServiceNotFoundException is returned by ListTasks
	_ = &ServiceNotFoundException{}

	// ClientException is returned by PutAccountSetting
	_ = &ClientException{}

	// InvalidParameterException is returned by PutAccountSetting
	_ = &InvalidParameterException{}

	// ServerException is returned by PutAccountSetting
	_ = &ServerException{}

	// ClientException is returned by PutAccountSettingDefault
	_ = &ClientException{}

	// InvalidParameterException is returned by PutAccountSettingDefault
	_ = &InvalidParameterException{}

	// ServerException is returned by PutAccountSettingDefault
	_ = &ServerException{}

	// AttributeLimitExceededException is returned by PutAttributes
	_ = &AttributeLimitExceededException{}

	// ClusterNotFoundException is returned by PutAttributes
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by PutAttributes
	_ = &InvalidParameterException{}

	// TargetNotFoundException is returned by PutAttributes
	_ = &TargetNotFoundException{}

	// ClientException is returned by PutClusterCapacityProviders
	_ = &ClientException{}

	// ClusterNotFoundException is returned by PutClusterCapacityProviders
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by PutClusterCapacityProviders
	_ = &InvalidParameterException{}

	// ResourceInUseException is returned by PutClusterCapacityProviders
	_ = &ResourceInUseException{}

	// ServerException is returned by PutClusterCapacityProviders
	_ = &ServerException{}

	// UpdateInProgressException is returned by PutClusterCapacityProviders
	_ = &UpdateInProgressException{}

	// ClientException is returned by RegisterContainerInstance
	_ = &ClientException{}

	// InvalidParameterException is returned by RegisterContainerInstance
	_ = &InvalidParameterException{}

	// ServerException is returned by RegisterContainerInstance
	_ = &ServerException{}

	// ClientException is returned by RegisterTaskDefinition
	_ = &ClientException{}

	// InvalidParameterException is returned by RegisterTaskDefinition
	_ = &InvalidParameterException{}

	// ServerException is returned by RegisterTaskDefinition
	_ = &ServerException{}

	// AccessDeniedException is returned by RunTask
	_ = &AccessDeniedException{}

	// BlockedException is returned by RunTask
	_ = &BlockedException{}

	// ClientException is returned by RunTask
	_ = &ClientException{}

	// ClusterNotFoundException is returned by RunTask
	_ = &ClusterNotFoundException{}

	// ConflictException is returned by RunTask
	_ = &ConflictException{}

	// InvalidParameterException is returned by RunTask
	_ = &InvalidParameterException{}

	// PlatformTaskDefinitionIncompatibilityException is returned by RunTask
	_ = &PlatformTaskDefinitionIncompatibilityException{}

	// PlatformUnknownException is returned by RunTask
	_ = &PlatformUnknownException{}

	// ServerException is returned by RunTask
	_ = &ServerException{}

	// UnsupportedFeatureException is returned by RunTask
	_ = &UnsupportedFeatureException{}

	// ClientException is returned by StartTask
	_ = &ClientException{}

	// ClusterNotFoundException is returned by StartTask
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by StartTask
	_ = &InvalidParameterException{}

	// ServerException is returned by StartTask
	_ = &ServerException{}

	// UnsupportedFeatureException is returned by StartTask
	_ = &UnsupportedFeatureException{}

	// AccessDeniedException is returned by StopServiceDeployment
	_ = &AccessDeniedException{}

	// ClientException is returned by StopServiceDeployment
	_ = &ClientException{}

	// ConflictException is returned by StopServiceDeployment
	_ = &ConflictException{}

	// InvalidParameterException is returned by StopServiceDeployment
	_ = &InvalidParameterException{}

	// ServerException is returned by StopServiceDeployment
	_ = &ServerException{}

	// ServiceDeploymentNotFoundException is returned by StopServiceDeployment
	_ = &ServiceDeploymentNotFoundException{}

	// UnsupportedFeatureException is returned by StopServiceDeployment
	_ = &UnsupportedFeatureException{}

	// ClientException is returned by StopTask
	_ = &ClientException{}

	// ClusterNotFoundException is returned by StopTask
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by StopTask
	_ = &InvalidParameterException{}

	// ServerException is returned by StopTask
	_ = &ServerException{}

	// AccessDeniedException is returned by SubmitAttachmentStateChanges
	_ = &AccessDeniedException{}

	// ClientException is returned by SubmitAttachmentStateChanges
	_ = &ClientException{}

	// InvalidParameterException is returned by SubmitAttachmentStateChanges
	_ = &InvalidParameterException{}

	// ServerException is returned by SubmitAttachmentStateChanges
	_ = &ServerException{}

	// AccessDeniedException is returned by SubmitContainerStateChange
	_ = &AccessDeniedException{}

	// ClientException is returned by SubmitContainerStateChange
	_ = &ClientException{}

	// ServerException is returned by SubmitContainerStateChange
	_ = &ServerException{}

	// AccessDeniedException is returned by SubmitTaskStateChange
	_ = &AccessDeniedException{}

	// ClientException is returned by SubmitTaskStateChange
	_ = &ClientException{}

	// InvalidParameterException is returned by SubmitTaskStateChange
	_ = &InvalidParameterException{}

	// ServerException is returned by SubmitTaskStateChange
	_ = &ServerException{}

	// ClientException is returned by TagResource
	_ = &ClientException{}

	// ClusterNotFoundException is returned by TagResource
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by TagResource
	_ = &InvalidParameterException{}

	// ResourceNotFoundException is returned by TagResource
	_ = &ResourceNotFoundException{}

	// ServerException is returned by TagResource
	_ = &ServerException{}

	// ClientException is returned by UntagResource
	_ = &ClientException{}

	// ClusterNotFoundException is returned by UntagResource
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by UntagResource
	_ = &InvalidParameterException{}

	// ResourceNotFoundException is returned by UntagResource
	_ = &ResourceNotFoundException{}

	// ServerException is returned by UntagResource
	_ = &ServerException{}

	// ClientException is returned by UpdateCapacityProvider
	_ = &ClientException{}

	// InvalidParameterException is returned by UpdateCapacityProvider
	_ = &InvalidParameterException{}

	// ServerException is returned by UpdateCapacityProvider
	_ = &ServerException{}

	// ClientException is returned by UpdateCluster
	_ = &ClientException{}

	// ClusterNotFoundException is returned by UpdateCluster
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by UpdateCluster
	_ = &InvalidParameterException{}

	// NamespaceNotFoundException is returned by UpdateCluster
	_ = &NamespaceNotFoundException{}

	// ServerException is returned by UpdateCluster
	_ = &ServerException{}

	// ClientException is returned by UpdateClusterSettings
	_ = &ClientException{}

	// ClusterNotFoundException is returned by UpdateClusterSettings
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by UpdateClusterSettings
	_ = &InvalidParameterException{}

	// ServerException is returned by UpdateClusterSettings
	_ = &ServerException{}

	// ClientException is returned by UpdateContainerAgent
	_ = &ClientException{}

	// ClusterNotFoundException is returned by UpdateContainerAgent
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by UpdateContainerAgent
	_ = &InvalidParameterException{}

	// MissingVersionException is returned by UpdateContainerAgent
	_ = &MissingVersionException{}

	// NoUpdateAvailableException is returned by UpdateContainerAgent
	_ = &NoUpdateAvailableException{}

	// ServerException is returned by UpdateContainerAgent
	_ = &ServerException{}

	// UpdateInProgressException is returned by UpdateContainerAgent
	_ = &UpdateInProgressException{}

	// ClientException is returned by UpdateContainerInstancesState
	_ = &ClientException{}

	// ClusterNotFoundException is returned by UpdateContainerInstancesState
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by UpdateContainerInstancesState
	_ = &InvalidParameterException{}

	// ServerException is returned by UpdateContainerInstancesState
	_ = &ServerException{}

	// AccessDeniedException is returned by UpdateService
	_ = &AccessDeniedException{}

	// ClientException is returned by UpdateService
	_ = &ClientException{}

	// ClusterNotFoundException is returned by UpdateService
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by UpdateService
	_ = &InvalidParameterException{}

	// NamespaceNotFoundException is returned by UpdateService
	_ = &NamespaceNotFoundException{}

	// PlatformTaskDefinitionIncompatibilityException is returned by UpdateService
	_ = &PlatformTaskDefinitionIncompatibilityException{}

	// PlatformUnknownException is returned by UpdateService
	_ = &PlatformUnknownException{}

	// ServerException is returned by UpdateService
	_ = &ServerException{}

	// ServiceNotActiveException is returned by UpdateService
	_ = &ServiceNotActiveException{}

	// ServiceNotFoundException is returned by UpdateService
	_ = &ServiceNotFoundException{}

	// UnsupportedFeatureException is returned by UpdateService
	_ = &UnsupportedFeatureException{}

	// AccessDeniedException is returned by UpdateServicePrimaryTaskSet
	_ = &AccessDeniedException{}

	// ClientException is returned by UpdateServicePrimaryTaskSet
	_ = &ClientException{}

	// ClusterNotFoundException is returned by UpdateServicePrimaryTaskSet
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by UpdateServicePrimaryTaskSet
	_ = &InvalidParameterException{}

	// ServerException is returned by UpdateServicePrimaryTaskSet
	_ = &ServerException{}

	// ServiceNotActiveException is returned by UpdateServicePrimaryTaskSet
	_ = &ServiceNotActiveException{}

	// ServiceNotFoundException is returned by UpdateServicePrimaryTaskSet
	_ = &ServiceNotFoundException{}

	// TaskSetNotFoundException is returned by UpdateServicePrimaryTaskSet
	_ = &TaskSetNotFoundException{}

	// UnsupportedFeatureException is returned by UpdateServicePrimaryTaskSet
	_ = &UnsupportedFeatureException{}

	// AccessDeniedException is returned by UpdateTaskProtection
	_ = &AccessDeniedException{}

	// ClientException is returned by UpdateTaskProtection
	_ = &ClientException{}

	// ClusterNotFoundException is returned by UpdateTaskProtection
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by UpdateTaskProtection
	_ = &InvalidParameterException{}

	// ResourceNotFoundException is returned by UpdateTaskProtection
	_ = &ResourceNotFoundException{}

	// ServerException is returned by UpdateTaskProtection
	_ = &ServerException{}

	// UnsupportedFeatureException is returned by UpdateTaskProtection
	_ = &UnsupportedFeatureException{}

	// AccessDeniedException is returned by UpdateTaskSet
	_ = &AccessDeniedException{}

	// ClientException is returned by UpdateTaskSet
	_ = &ClientException{}

	// ClusterNotFoundException is returned by UpdateTaskSet
	_ = &ClusterNotFoundException{}

	// InvalidParameterException is returned by UpdateTaskSet
	_ = &InvalidParameterException{}

	// ServerException is returned by UpdateTaskSet
	_ = &ServerException{}

	// ServiceNotActiveException is returned by UpdateTaskSet
	_ = &ServiceNotActiveException{}

	// ServiceNotFoundException is returned by UpdateTaskSet
	_ = &ServiceNotFoundException{}

	// TaskSetNotFoundException is returned by UpdateTaskSet
	_ = &TaskSetNotFoundException{}

	// UnsupportedFeatureException is returned by UpdateTaskSet
	_ = &UnsupportedFeatureException{}
)
