# Production configuration for KECS Control Plane

# Server configuration
server:
  port: 8080
  adminPort: 8081
  readTimeout: 30s
  writeTimeout: 30s
  idleTimeout: 120s
  shutdownTimeout: 30s

# WebSocket configuration
websocket:
  allowedOrigins:
    # Development
    - "http://localhost:3000"
    - "http://localhost:8080"
    # Production - replace with actual domains
    # - "https://app.example.com"
    # - "*.example.com"
  allowCredentials: true
  
# Security configuration
security:
  cors:
    enabled: true
    allowedOrigins:
      - "*"  # In production, specify actual domains
    allowedMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - PATCH
    allowedHeaders:
      - Accept
      - Authorization
      - Content-Type
      - X-CSRF-Token
      - X-Amz-Target
      - X-Amz-Date
      - X-Amz-Security-Token
      - X-Amz-User-Agent
    allowCredentials: true
    maxAge: 86400

# Storage configuration
storage:
  type: duckdb
  duckdb:
    path: "/data/kecs.db"
    inMemory: false
    readOnly: false

# Kubernetes configuration
kubernetes:
  inCluster: true  # Use in-cluster config when running in Kubernetes
  kubeconfig: ""   # Empty for in-cluster

# Logging configuration
logging:
  level: info
  format: json
  output: stdout

# Metrics configuration
metrics:
  enabled: true
  path: /metrics
  
# Health check configuration
health:
  enabled: true
  path: /health
  readinessPath: /ready
  livenessPath: /live

# LocalStack configuration
localstack:
  enabled: false  # Set to true to enable LocalStack integration
  services:
    - iam
    - logs
    - ssm
    - secretsmanager
    - elbv2
  persistence: true
  image: "localstack/localstack"
  version: "latest"
  namespace: "aws-services"
  port: 4566
  edgePort: 4566
  resources:
    memory: "2Gi"
    cpu: "1000m"
    storageSize: "10Gi"
  environment:
    DEFAULT_REGION: "us-east-1"
    DOCKER_HOST: "unix:///var/run/docker.sock"
    LAMBDA_EXECUTOR: "local"
    DISABLE_CORS_CHECKS: "1"
    DISABLE_CUSTOM_CORS_S3: "1"
    EXTRA_CORS_ALLOWED_ORIGINS: "*"
    EXTRA_CORS_ALLOWED_HEADERS: "x-amz-*"
  debug: false
  dataDir: "/var/lib/localstack"
  
# AWS Proxy configuration  
proxy:
  mode: "environment"  # Options: environment, sidecar, ebpf, disabled
  localstackEndpoint: "http://localstack.aws-services.svc.cluster.local:4566"
  fallbackEnabled: true
  fallbackOrder:
    - sidecar
    - environment