apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kecs-system
  labels:
    app: traefik
    kecs.dev/component: "gateway"
data:
  traefik.yaml: |
    api:
      dashboard: true
      debug: true
    
    entryPoints:
      web:
        address: ":80"
      aws:
        address: ":4566"
      metrics:
        address: ":8082"
    
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        allowExternalNameServices: true
      kubernetesIngress:
        allowExternalNameServices: true
    
    log:
      level: INFO
      format: json
    
    accessLog:
      format: json
      fields:
        defaultMode: keep
        headers:
          defaultMode: keep
          names:
            X-Amz-Target: keep
            Authorization: redact
    
    metrics:
      prometheus:
        entryPoint: metrics
        addEntryPointsLabels: true
        addServicesLabels: true
    
    ping:
      entryPoint: web