apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ingressroutes.traefik.io
  labels:
    kecs.dev/component: "gateway"
spec:
  group: traefik.io
  names:
    kind: IngressRoute
    plural: ingressroutes
    singular: ingressroute
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              entryPoints:
                type: array
                items:
                  type: string
              routes:
                type: array
                items:
                  type: object
                  properties:
                    match:
                      type: string
                    kind:
                      type: string
                    priority:
                      type: integer
                    services:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          port:
                            x-kubernetes-int-or-string: true
                          namespace:
                            type: string
                          weight:
                            type: integer
                    middlewares:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: middlewares.traefik.io
  labels:
    kecs.dev/component: "gateway"
spec:
  group: traefik.io
  names:
    kind: Middleware
    plural: middlewares
    singular: middleware
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true