# Webhook Service
apiVersion: v1
kind: Service
metadata:
  name: kecs-webhook
  namespace: kecs-system
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8443
  selector:
    app: kecs-controlplane
---
# RBAC for webhook
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kecs-webhook
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kecs-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kecs-webhook
subjects:
- kind: ServiceAccount
  name: kecs-controlplane
  namespace: kecs-system