apiVersion: apps/v1
kind: Deployment
metadata:
  name: kecs-controlplane
  namespace: kecs-system
  labels:
    app: kecs-controlplane
    component: controlplane
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kecs-controlplane
  template:
    metadata:
      labels:
        app: kecs-controlplane
        component: controlplane
    spec:
      serviceAccountName: kecs-controlplane
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
      containers:
      - name: controlplane
        image: ghcr.io/nandemo-ya/kecs:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: admin
          containerPort: 8081
          protocol: TCP
        env:
        - name: PORT
          value: "8080"
        - name: ADMIN_PORT
          value: "8081"
        - name: KECS_UI_ENABLED
          value: "true"
        - name: KECS_UI_BASE_PATH
          value: "/ui"
        - name: KECS_STORAGE_TYPE
          value: "duckdb"
        - name: KECS_STORAGE_PATH
          value: "/data/kecs.db"
        - name: KECS_LOG_LEVEL
          value: "info"
        - name: KECS_LOG_FORMAT
          value: "json"
        - name: KECS_IN_CLUSTER
          value: "true"
        - name: AWS_REGION
          value: "us-east-1"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: admin
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: admin
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: kecs-controlplane-data
---
apiVersion: v1
kind: Service
metadata:
  name: kecs-controlplane
  namespace: kecs-system
  labels:
    app: kecs-controlplane
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: admin
    port: 8081
    targetPort: admin
    protocol: TCP
  selector:
    app: kecs-controlplane
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kecs-controlplane-data
  namespace: kecs-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard