#!/bin/bash
# Script to generate logo variants
# This script provides instructions for generating logo variants since image conversion tools are not available

echo "KECS Logo Variant Generation Instructions"
echo "========================================"
echo ""
echo "To generate logo variants (PNG, favicon), you'll need to use one of these methods:"
echo ""
echo "Method 1: Using ImageMagick (recommended)"
echo "  brew install imagemagick"
echo "  convert assets/logo.svg -resize 512x512 docs-site/public/logo-512.png"
echo "  convert assets/logo.svg -resize 256x256 docs-site/public/logo-256.png"
echo "  convert assets/logo.svg -resize 128x128 docs-site/public/logo-128.png"
echo "  convert assets/logo.svg -resize 64x64 docs-site/public/logo-64.png"
echo "  convert assets/logo.svg -resize 32x32 docs-site/public/favicon-32.png"
echo "  convert assets/logo.svg -resize 16x16 docs-site/public/favicon-16.png"
echo ""
echo "Method 2: Using rsvg-convert"
echo "  brew install librsvg"
echo "  rsvg-convert -w 512 -h 512 assets/logo.svg > docs-site/public/logo-512.png"
echo "  rsvg-convert -w 32 -h 32 assets/logo.svg > docs-site/public/favicon-32.png"
echo ""
echo "Method 3: Using online tools"
echo "  1. Visit https://cloudconvert.com/svg-to-png"
echo "  2. Upload assets/logo.svg"
echo "  3. Generate variants at sizes: 512x512, 256x256, 128x128, 64x64, 32x32, 16x16"
echo "  4. Save to docs-site/public/"
echo ""
echo "Method 4: Using macOS Preview app"
echo "  1. Open assets/logo.svg in Preview"
echo "  2. File > Export..."
echo "  3. Format: PNG"
echo "  4. Save different sizes"
echo ""
echo "After generating the images, update:"
echo "  - docs-site/public/favicon.ico (convert from 32x32 PNG)"
echo "  - Add apple-touch-icon.png (180x180) for mobile devices"