// Code generated by cmd/codegen. DO NOT EDIT.

package generated_elbv2

// ActionTypeEnum represents the ActionTypeEnum enum type
type ActionTypeEnum string

const (
	ActionTypeEnumREDIRECT ActionTypeEnum = "REDIRECT"

	ActionTypeEnumFIXED_RESPONSE ActionTypeEnum = "FIXED_RESPONSE"

	ActionTypeEnumFORWARD ActionTypeEnum = "FORWARD"

	ActionTypeEnumAUTHENTICATE_OIDC ActionTypeEnum = "AUTHENTICATE_OIDC"

	ActionTypeEnumAUTHENTICATE_COGNITO ActionTypeEnum = "AUTHENTICATE_COGNITO"
)

// AdvertiseTrustStoreCaNamesEnum represents the AdvertiseTrustStoreCaNamesEnum enum type
type AdvertiseTrustStoreCaNamesEnum string

const (
	AdvertiseTrustStoreCaNamesEnumoff AdvertiseTrustStoreCaNamesEnum = "off"

	AdvertiseTrustStoreCaNamesEnumon AdvertiseTrustStoreCaNamesEnum = "on"
)

// AnomalyResultEnum represents the AnomalyResultEnum enum type
type AnomalyResultEnum string

const (
	AnomalyResultEnumNORMAL AnomalyResultEnum = "NORMAL"

	AnomalyResultEnumANOMALOUS AnomalyResultEnum = "ANOMALOUS"
)

// AuthenticateCognitoActionConditionalBehaviorEnum represents the AuthenticateCognitoActionConditionalBehaviorEnum enum type
type AuthenticateCognitoActionConditionalBehaviorEnum string

const (
	AuthenticateCognitoActionConditionalBehaviorEnumALLOW AuthenticateCognitoActionConditionalBehaviorEnum = "ALLOW"

	AuthenticateCognitoActionConditionalBehaviorEnumAUTHENTICATE AuthenticateCognitoActionConditionalBehaviorEnum = "AUTHENTICATE"

	AuthenticateCognitoActionConditionalBehaviorEnumDENY AuthenticateCognitoActionConditionalBehaviorEnum = "DENY"
)

// AuthenticateOidcActionConditionalBehaviorEnum represents the AuthenticateOidcActionConditionalBehaviorEnum enum type
type AuthenticateOidcActionConditionalBehaviorEnum string

const (
	AuthenticateOidcActionConditionalBehaviorEnumAUTHENTICATE AuthenticateOidcActionConditionalBehaviorEnum = "AUTHENTICATE"

	AuthenticateOidcActionConditionalBehaviorEnumDENY AuthenticateOidcActionConditionalBehaviorEnum = "DENY"

	AuthenticateOidcActionConditionalBehaviorEnumALLOW AuthenticateOidcActionConditionalBehaviorEnum = "ALLOW"
)

// CapacityReservationStateEnum represents the CapacityReservationStateEnum enum type
type CapacityReservationStateEnum string

const (
	CapacityReservationStateEnumPROVISIONED CapacityReservationStateEnum = "PROVISIONED"

	CapacityReservationStateEnumPENDING CapacityReservationStateEnum = "PENDING"

	CapacityReservationStateEnumREBALANCING CapacityReservationStateEnum = "REBALANCING"

	CapacityReservationStateEnumFAILED CapacityReservationStateEnum = "FAILED"
)

// DescribeTargetHealthInputIncludeEnum represents the DescribeTargetHealthInputIncludeEnum enum type
type DescribeTargetHealthInputIncludeEnum string

const (
	DescribeTargetHealthInputIncludeEnumALL DescribeTargetHealthInputIncludeEnum = "ALL"

	DescribeTargetHealthInputIncludeEnumANOMALY DescribeTargetHealthInputIncludeEnum = "ANOMALY"
)

// EnablePrefixForIpv6SourceNatEnum represents the EnablePrefixForIpv6SourceNatEnum enum type
type EnablePrefixForIpv6SourceNatEnum string

const (
	EnablePrefixForIpv6SourceNatEnumOFF EnablePrefixForIpv6SourceNatEnum = "OFF"

	EnablePrefixForIpv6SourceNatEnumON EnablePrefixForIpv6SourceNatEnum = "ON"
)

// EnforceSecurityGroupInboundRulesOnPrivateLinkTrafficEnum represents the EnforceSecurityGroupInboundRulesOnPrivateLinkTrafficEnum enum type
type EnforceSecurityGroupInboundRulesOnPrivateLinkTrafficEnum string

const (
	EnforceSecurityGroupInboundRulesOnPrivateLinkTrafficEnumon EnforceSecurityGroupInboundRulesOnPrivateLinkTrafficEnum = "on"

	EnforceSecurityGroupInboundRulesOnPrivateLinkTrafficEnumoff EnforceSecurityGroupInboundRulesOnPrivateLinkTrafficEnum = "off"
)

// IpAddressType represents the IpAddressType enum type
type IpAddressType string

const (
	IpAddressTypeIPV4 IpAddressType = "IPV4"

	IpAddressTypeDUALSTACK IpAddressType = "DUALSTACK"

	IpAddressTypeDUALSTACK_WITHOUT_PUBLIC_IPV4 IpAddressType = "DUALSTACK_WITHOUT_PUBLIC_IPV4"
)

// LoadBalancerSchemeEnum represents the LoadBalancerSchemeEnum enum type
type LoadBalancerSchemeEnum string

const (
	LoadBalancerSchemeEnumINTERNET_FACING LoadBalancerSchemeEnum = "INTERNET_FACING"

	LoadBalancerSchemeEnumINTERNAL LoadBalancerSchemeEnum = "INTERNAL"
)

// LoadBalancerStateEnum represents the LoadBalancerStateEnum enum type
type LoadBalancerStateEnum string

const (
	LoadBalancerStateEnumPROVISIONING LoadBalancerStateEnum = "PROVISIONING"

	LoadBalancerStateEnumACTIVE_IMPAIRED LoadBalancerStateEnum = "ACTIVE_IMPAIRED"

	LoadBalancerStateEnumFAILED LoadBalancerStateEnum = "FAILED"

	LoadBalancerStateEnumACTIVE LoadBalancerStateEnum = "ACTIVE"
)

// LoadBalancerTypeEnum represents the LoadBalancerTypeEnum enum type
type LoadBalancerTypeEnum string

const (
	LoadBalancerTypeEnumAPPLICATION LoadBalancerTypeEnum = "APPLICATION"

	LoadBalancerTypeEnumNETWORK LoadBalancerTypeEnum = "NETWORK"

	LoadBalancerTypeEnumGATEWAY LoadBalancerTypeEnum = "GATEWAY"
)

// MitigationInEffectEnum represents the MitigationInEffectEnum enum type
type MitigationInEffectEnum string

const (
	MitigationInEffectEnumYES MitigationInEffectEnum = "YES"

	MitigationInEffectEnumNO MitigationInEffectEnum = "NO"
)

// ProtocolEnum represents the ProtocolEnum enum type
type ProtocolEnum string

const (
	ProtocolEnumTLS ProtocolEnum = "TLS"

	ProtocolEnumUDP ProtocolEnum = "UDP"

	ProtocolEnumTCP_UDP ProtocolEnum = "TCP_UDP"

	ProtocolEnumGENEVE ProtocolEnum = "GENEVE"

	ProtocolEnumHTTP ProtocolEnum = "HTTP"

	ProtocolEnumHTTPS ProtocolEnum = "HTTPS"

	ProtocolEnumTCP ProtocolEnum = "TCP"
)

// RedirectActionStatusCodeEnum represents the RedirectActionStatusCodeEnum enum type
type RedirectActionStatusCodeEnum string

const (
	RedirectActionStatusCodeEnumHTTP_301 RedirectActionStatusCodeEnum = "HTTP_301"

	RedirectActionStatusCodeEnumHTTP_302 RedirectActionStatusCodeEnum = "HTTP_302"
)

// RemoveIpamPoolEnum represents the RemoveIpamPoolEnum enum type
type RemoveIpamPoolEnum string

const (
	RemoveIpamPoolEnumipv4 RemoveIpamPoolEnum = "ipv4"
)

// RevocationType represents the RevocationType enum type
type RevocationType string

const (
	RevocationTypeCRL RevocationType = "CRL"
)

// TargetAdministrativeOverrideReasonEnum represents the TargetAdministrativeOverrideReasonEnum enum type
type TargetAdministrativeOverrideReasonEnum string

const (
	TargetAdministrativeOverrideReasonEnumINTERNAL_ERROR TargetAdministrativeOverrideReasonEnum = "INTERNAL_ERROR"

	TargetAdministrativeOverrideReasonEnumNO_OVERRIDE_ENGAGED TargetAdministrativeOverrideReasonEnum = "NO_OVERRIDE_ENGAGED"

	TargetAdministrativeOverrideReasonEnumZONAL_SHIFT_ENGAGED TargetAdministrativeOverrideReasonEnum = "ZONAL_SHIFT_ENGAGED"

	TargetAdministrativeOverrideReasonEnumZONAL_SHIFT_DELEGATED_TO_DNS TargetAdministrativeOverrideReasonEnum = "ZONAL_SHIFT_DELEGATED_TO_DNS"
)

// TargetAdministrativeOverrideStateEnum represents the TargetAdministrativeOverrideStateEnum enum type
type TargetAdministrativeOverrideStateEnum string

const (
	TargetAdministrativeOverrideStateEnumZONAL_SHIFT_DELEGATED_TO_DNS TargetAdministrativeOverrideStateEnum = "ZONAL_SHIFT_DELEGATED_TO_DNS"

	TargetAdministrativeOverrideStateEnumUNKNOWN TargetAdministrativeOverrideStateEnum = "UNKNOWN"

	TargetAdministrativeOverrideStateEnumNO_OVERRIDE TargetAdministrativeOverrideStateEnum = "NO_OVERRIDE"

	TargetAdministrativeOverrideStateEnumZONAL_SHIFT_ACTIVE TargetAdministrativeOverrideStateEnum = "ZONAL_SHIFT_ACTIVE"
)

// TargetGroupIpAddressTypeEnum represents the TargetGroupIpAddressTypeEnum enum type
type TargetGroupIpAddressTypeEnum string

const (
	TargetGroupIpAddressTypeEnumIPV4 TargetGroupIpAddressTypeEnum = "IPV4"

	TargetGroupIpAddressTypeEnumIPV6 TargetGroupIpAddressTypeEnum = "IPV6"
)

// TargetHealthReasonEnum represents the TargetHealthReasonEnum enum type
type TargetHealthReasonEnum string

const (
	TargetHealthReasonEnumTIMEOUT TargetHealthReasonEnum = "TIMEOUT"

	TargetHealthReasonEnumFAILED_HEALTH_CHECKS TargetHealthReasonEnum = "FAILED_HEALTH_CHECKS"

	TargetHealthReasonEnumNOT_REGISTERED TargetHealthReasonEnum = "NOT_REGISTERED"

	TargetHealthReasonEnumINVALID_STATE TargetHealthReasonEnum = "INVALID_STATE"

	TargetHealthReasonEnumHEALTH_CHECK_DISABLED TargetHealthReasonEnum = "HEALTH_CHECK_DISABLED"

	TargetHealthReasonEnumREGISTRATION_IN_PROGRESS TargetHealthReasonEnum = "REGISTRATION_IN_PROGRESS"

	TargetHealthReasonEnumRESPONSE_CODE_MISMATCH TargetHealthReasonEnum = "RESPONSE_CODE_MISMATCH"

	TargetHealthReasonEnumNOT_IN_USE TargetHealthReasonEnum = "NOT_IN_USE"

	TargetHealthReasonEnumDEREGISTRATION_IN_PROGRESS TargetHealthReasonEnum = "DEREGISTRATION_IN_PROGRESS"

	TargetHealthReasonEnumIP_UNUSABLE TargetHealthReasonEnum = "IP_UNUSABLE"

	TargetHealthReasonEnumINTERNAL_ERROR TargetHealthReasonEnum = "INTERNAL_ERROR"

	TargetHealthReasonEnumINITIAL_HEALTH_CHECKING TargetHealthReasonEnum = "INITIAL_HEALTH_CHECKING"
)

// TargetHealthStateEnum represents the TargetHealthStateEnum enum type
type TargetHealthStateEnum string

const (
	TargetHealthStateEnumUNHEALTHY_DRAINING TargetHealthStateEnum = "UNHEALTHY_DRAINING"

	TargetHealthStateEnumUNUSED TargetHealthStateEnum = "UNUSED"

	TargetHealthStateEnumDRAINING TargetHealthStateEnum = "DRAINING"

	TargetHealthStateEnumUNAVAILABLE TargetHealthStateEnum = "UNAVAILABLE"

	TargetHealthStateEnumINITIAL TargetHealthStateEnum = "INITIAL"

	TargetHealthStateEnumHEALTHY TargetHealthStateEnum = "HEALTHY"

	TargetHealthStateEnumUNHEALTHY TargetHealthStateEnum = "UNHEALTHY"
)

// TargetTypeEnum represents the TargetTypeEnum enum type
type TargetTypeEnum string

const (
	TargetTypeEnumINSTANCE TargetTypeEnum = "INSTANCE"

	TargetTypeEnumIP TargetTypeEnum = "IP"

	TargetTypeEnumLAMBDA TargetTypeEnum = "LAMBDA"

	TargetTypeEnumALB TargetTypeEnum = "ALB"
)

// TrustStoreAssociationStatusEnum represents the TrustStoreAssociationStatusEnum enum type
type TrustStoreAssociationStatusEnum string

const (
	TrustStoreAssociationStatusEnumREMOVED TrustStoreAssociationStatusEnum = "REMOVED"

	TrustStoreAssociationStatusEnumACTIVE TrustStoreAssociationStatusEnum = "ACTIVE"
)

// TrustStoreStatus represents the TrustStoreStatus enum type
type TrustStoreStatus string

const (
	TrustStoreStatusACTIVE TrustStoreStatus = "ACTIVE"

	TrustStoreStatusCREATING TrustStoreStatus = "CREATING"
)
