// Code generated by cmd/codegen. DO NOT EDIT.

package generated_elbv2

// ActionTypeEnum represents the ActionTypeEnum enum type
type ActionTypeEnum string

const (
	ActionTypeEnumREDIRECT ActionTypeEnum = "redirect"

	ActionTypeEnumFIXED_RESPONSE ActionTypeEnum = "fixed-response"

	ActionTypeEnumFORWARD ActionTypeEnum = "forward"

	ActionTypeEnumAUTHENTICATE_OIDC ActionTypeEnum = "authenticate-oidc"

	ActionTypeEnumAUTHENTICATE_COGNITO ActionTypeEnum = "authenticate-cognito"
)

// AdvertiseTrustStoreCaNamesEnum represents the AdvertiseTrustStoreCaNamesEnum enum type
type AdvertiseTrustStoreCaNamesEnum string

const (
	AdvertiseTrustStoreCaNamesEnumon AdvertiseTrustStoreCaNamesEnum = "on"

	AdvertiseTrustStoreCaNamesEnumoff AdvertiseTrustStoreCaNamesEnum = "off"
)

// AnomalyResultEnum represents the AnomalyResultEnum enum type
type AnomalyResultEnum string

const (
	AnomalyResultEnumANOMALOUS AnomalyResultEnum = "anomalous"

	AnomalyResultEnumNORMAL AnomalyResultEnum = "normal"
)

// AuthenticateCognitoActionConditionalBehaviorEnum represents the AuthenticateCognitoActionConditionalBehaviorEnum enum type
type AuthenticateCognitoActionConditionalBehaviorEnum string

const (
	AuthenticateCognitoActionConditionalBehaviorEnumDENY AuthenticateCognitoActionConditionalBehaviorEnum = "deny"

	AuthenticateCognitoActionConditionalBehaviorEnumALLOW AuthenticateCognitoActionConditionalBehaviorEnum = "allow"

	AuthenticateCognitoActionConditionalBehaviorEnumAUTHENTICATE AuthenticateCognitoActionConditionalBehaviorEnum = "authenticate"
)

// AuthenticateOidcActionConditionalBehaviorEnum represents the AuthenticateOidcActionConditionalBehaviorEnum enum type
type AuthenticateOidcActionConditionalBehaviorEnum string

const (
	AuthenticateOidcActionConditionalBehaviorEnumDENY AuthenticateOidcActionConditionalBehaviorEnum = "deny"

	AuthenticateOidcActionConditionalBehaviorEnumALLOW AuthenticateOidcActionConditionalBehaviorEnum = "allow"

	AuthenticateOidcActionConditionalBehaviorEnumAUTHENTICATE AuthenticateOidcActionConditionalBehaviorEnum = "authenticate"
)

// CapacityReservationStateEnum represents the CapacityReservationStateEnum enum type
type CapacityReservationStateEnum string

const (
	CapacityReservationStateEnumREBALANCING CapacityReservationStateEnum = "rebalancing"

	CapacityReservationStateEnumFAILED CapacityReservationStateEnum = "failed"

	CapacityReservationStateEnumPROVISIONED CapacityReservationStateEnum = "provisioned"

	CapacityReservationStateEnumPENDING CapacityReservationStateEnum = "pending"
)

// DescribeTargetHealthInputIncludeEnum represents the DescribeTargetHealthInputIncludeEnum enum type
type DescribeTargetHealthInputIncludeEnum string

const (
	DescribeTargetHealthInputIncludeEnumANOMALY DescribeTargetHealthInputIncludeEnum = "AnomalyDetection"

	DescribeTargetHealthInputIncludeEnumALL DescribeTargetHealthInputIncludeEnum = "All"
)

// EnablePrefixForIpv6SourceNatEnum represents the EnablePrefixForIpv6SourceNatEnum enum type
type EnablePrefixForIpv6SourceNatEnum string

const (
	EnablePrefixForIpv6SourceNatEnumON EnablePrefixForIpv6SourceNatEnum = "on"

	EnablePrefixForIpv6SourceNatEnumOFF EnablePrefixForIpv6SourceNatEnum = "off"
)

// EnforceSecurityGroupInboundRulesOnPrivateLinkTrafficEnum represents the EnforceSecurityGroupInboundRulesOnPrivateLinkTrafficEnum enum type
type EnforceSecurityGroupInboundRulesOnPrivateLinkTrafficEnum string

const (
	EnforceSecurityGroupInboundRulesOnPrivateLinkTrafficEnumon EnforceSecurityGroupInboundRulesOnPrivateLinkTrafficEnum = "on"

	EnforceSecurityGroupInboundRulesOnPrivateLinkTrafficEnumoff EnforceSecurityGroupInboundRulesOnPrivateLinkTrafficEnum = "off"
)

// IpAddressType represents the IpAddressType enum type
type IpAddressType string

const (
	IpAddressTypeDUALSTACK_WITHOUT_PUBLIC_IPV4 IpAddressType = "dualstack-without-public-ipv4"

	IpAddressTypeIPV4 IpAddressType = "ipv4"

	IpAddressTypeDUALSTACK IpAddressType = "dualstack"
)

// LoadBalancerSchemeEnum represents the LoadBalancerSchemeEnum enum type
type LoadBalancerSchemeEnum string

const (
	LoadBalancerSchemeEnumINTERNET_FACING LoadBalancerSchemeEnum = "internet-facing"

	LoadBalancerSchemeEnumINTERNAL LoadBalancerSchemeEnum = "internal"
)

// LoadBalancerStateEnum represents the LoadBalancerStateEnum enum type
type LoadBalancerStateEnum string

const (
	LoadBalancerStateEnumACTIVE LoadBalancerStateEnum = "active"

	LoadBalancerStateEnumPROVISIONING LoadBalancerStateEnum = "provisioning"

	LoadBalancerStateEnumACTIVE_IMPAIRED LoadBalancerStateEnum = "active_impaired"

	LoadBalancerStateEnumFAILED LoadBalancerStateEnum = "failed"
)

// LoadBalancerTypeEnum represents the LoadBalancerTypeEnum enum type
type LoadBalancerTypeEnum string

const (
	LoadBalancerTypeEnumGATEWAY LoadBalancerTypeEnum = "gateway"

	LoadBalancerTypeEnumAPPLICATION LoadBalancerTypeEnum = "application"

	LoadBalancerTypeEnumNETWORK LoadBalancerTypeEnum = "network"
)

// MitigationInEffectEnum represents the MitigationInEffectEnum enum type
type MitigationInEffectEnum string

const (
	MitigationInEffectEnumYES MitigationInEffectEnum = "yes"

	MitigationInEffectEnumNO MitigationInEffectEnum = "no"
)

// ProtocolEnum represents the ProtocolEnum enum type
type ProtocolEnum string

const (
	ProtocolEnumHTTP ProtocolEnum = "HTTP"

	ProtocolEnumHTTPS ProtocolEnum = "HTTPS"

	ProtocolEnumTCP ProtocolEnum = "TCP"

	ProtocolEnumTLS ProtocolEnum = "TLS"

	ProtocolEnumUDP ProtocolEnum = "UDP"

	ProtocolEnumTCP_UDP ProtocolEnum = "TCP_UDP"

	ProtocolEnumGENEVE ProtocolEnum = "GENEVE"
)

// RedirectActionStatusCodeEnum represents the RedirectActionStatusCodeEnum enum type
type RedirectActionStatusCodeEnum string

const (
	RedirectActionStatusCodeEnumHTTP_301 RedirectActionStatusCodeEnum = "HTTP_301"

	RedirectActionStatusCodeEnumHTTP_302 RedirectActionStatusCodeEnum = "HTTP_302"
)

// RemoveIpamPoolEnum represents the RemoveIpamPoolEnum enum type
type RemoveIpamPoolEnum string

const (
	RemoveIpamPoolEnumipv4 RemoveIpamPoolEnum = "ipv4"
)

// RevocationType represents the RevocationType enum type
type RevocationType string

const (
	RevocationTypeCRL RevocationType = "CRL"
)

// TargetAdministrativeOverrideReasonEnum represents the TargetAdministrativeOverrideReasonEnum enum type
type TargetAdministrativeOverrideReasonEnum string

const (
	TargetAdministrativeOverrideReasonEnumINTERNAL_ERROR TargetAdministrativeOverrideReasonEnum = "AdministrativeOverride.Unknown"

	TargetAdministrativeOverrideReasonEnumNO_OVERRIDE_ENGAGED TargetAdministrativeOverrideReasonEnum = "AdministrativeOverride.NoOverride"

	TargetAdministrativeOverrideReasonEnumZONAL_SHIFT_ENGAGED TargetAdministrativeOverrideReasonEnum = "AdministrativeOverride.ZonalShiftActive"

	TargetAdministrativeOverrideReasonEnumZONAL_SHIFT_DELEGATED_TO_DNS TargetAdministrativeOverrideReasonEnum = "AdministrativeOverride.ZonalShiftDelegatedToDns"
)

// TargetAdministrativeOverrideStateEnum represents the TargetAdministrativeOverrideStateEnum enum type
type TargetAdministrativeOverrideStateEnum string

const (
	TargetAdministrativeOverrideStateEnumUNKNOWN TargetAdministrativeOverrideStateEnum = "unknown"

	TargetAdministrativeOverrideStateEnumNO_OVERRIDE TargetAdministrativeOverrideStateEnum = "no_override"

	TargetAdministrativeOverrideStateEnumZONAL_SHIFT_ACTIVE TargetAdministrativeOverrideStateEnum = "zonal_shift_active"

	TargetAdministrativeOverrideStateEnumZONAL_SHIFT_DELEGATED_TO_DNS TargetAdministrativeOverrideStateEnum = "zonal_shift_delegated_to_dns"
)

// TargetGroupIpAddressTypeEnum represents the TargetGroupIpAddressTypeEnum enum type
type TargetGroupIpAddressTypeEnum string

const (
	TargetGroupIpAddressTypeEnumIPV4 TargetGroupIpAddressTypeEnum = "ipv4"

	TargetGroupIpAddressTypeEnumIPV6 TargetGroupIpAddressTypeEnum = "ipv6"
)

// TargetHealthReasonEnum represents the TargetHealthReasonEnum enum type
type TargetHealthReasonEnum string

const (
	TargetHealthReasonEnumNOT_REGISTERED TargetHealthReasonEnum = "Target.NotRegistered"

	TargetHealthReasonEnumNOT_IN_USE TargetHealthReasonEnum = "Target.NotInUse"

	TargetHealthReasonEnumDEREGISTRATION_IN_PROGRESS TargetHealthReasonEnum = "Target.DeregistrationInProgress"

	TargetHealthReasonEnumINVALID_STATE TargetHealthReasonEnum = "Target.InvalidState"

	TargetHealthReasonEnumINTERNAL_ERROR TargetHealthReasonEnum = "Elb.InternalError"

	TargetHealthReasonEnumREGISTRATION_IN_PROGRESS TargetHealthReasonEnum = "Elb.RegistrationInProgress"

	TargetHealthReasonEnumINITIAL_HEALTH_CHECKING TargetHealthReasonEnum = "Elb.InitialHealthChecking"

	TargetHealthReasonEnumFAILED_HEALTH_CHECKS TargetHealthReasonEnum = "Target.FailedHealthChecks"

	TargetHealthReasonEnumIP_UNUSABLE TargetHealthReasonEnum = "Target.IpUnusable"

	TargetHealthReasonEnumHEALTH_CHECK_DISABLED TargetHealthReasonEnum = "Target.HealthCheckDisabled"

	TargetHealthReasonEnumRESPONSE_CODE_MISMATCH TargetHealthReasonEnum = "Target.ResponseCodeMismatch"

	TargetHealthReasonEnumTIMEOUT TargetHealthReasonEnum = "Target.Timeout"
)

// TargetHealthStateEnum represents the TargetHealthStateEnum enum type
type TargetHealthStateEnum string

const (
	TargetHealthStateEnumUNHEALTHY_DRAINING TargetHealthStateEnum = "unhealthy.draining"

	TargetHealthStateEnumUNUSED TargetHealthStateEnum = "unused"

	TargetHealthStateEnumDRAINING TargetHealthStateEnum = "draining"

	TargetHealthStateEnumUNAVAILABLE TargetHealthStateEnum = "unavailable"

	TargetHealthStateEnumINITIAL TargetHealthStateEnum = "initial"

	TargetHealthStateEnumHEALTHY TargetHealthStateEnum = "healthy"

	TargetHealthStateEnumUNHEALTHY TargetHealthStateEnum = "unhealthy"
)

// TargetTypeEnum represents the TargetTypeEnum enum type
type TargetTypeEnum string

const (
	TargetTypeEnumINSTANCE TargetTypeEnum = "instance"

	TargetTypeEnumIP TargetTypeEnum = "ip"

	TargetTypeEnumLAMBDA TargetTypeEnum = "lambda"

	TargetTypeEnumALB TargetTypeEnum = "alb"
)

// TrustStoreAssociationStatusEnum represents the TrustStoreAssociationStatusEnum enum type
type TrustStoreAssociationStatusEnum string

const (
	TrustStoreAssociationStatusEnumACTIVE TrustStoreAssociationStatusEnum = "active"

	TrustStoreAssociationStatusEnumREMOVED TrustStoreAssociationStatusEnum = "removed"
)

// TrustStoreStatus represents the TrustStoreStatus enum type
type TrustStoreStatus string

const (
	TrustStoreStatusACTIVE TrustStoreStatus = "ACTIVE"

	TrustStoreStatusCREATING TrustStoreStatus = "CREATING"
)
