// Code generated by cmd/codegen. DO NOT EDIT.

package generated_elbv2

import (
	"time"
)

// Unit represents an empty response
type Unit = struct{}

// ALPNPolicyNotSupportedException represents the ALPNPolicyNotSupportedException structure
type ALPNPolicyNotSupportedException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for ALPNPolicyNotSupportedException
func (e ALPNPolicyNotSupportedException) Error() string {
	return "ALPNPolicyNotSupportedException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e ALPNPolicyNotSupportedException) ErrorCode() string {
	return "ALPNPolicyNotSupportedException"
}

// ErrorFault indicates whether this is a client or server error
func (e ALPNPolicyNotSupportedException) ErrorFault() string {
	return "client"
}

// Action represents the Action structure
type Action struct {
	AuthenticateCognitoConfig *AuthenticateCognitoActionConfig `json:"authenticateCognitoConfig,omitempty"`

	AuthenticateOidcConfig *AuthenticateOidcActionConfig `json:"authenticateOidcConfig,omitempty"`

	FixedResponseConfig *FixedResponseActionConfig `json:"fixedResponseConfig,omitempty"`

	ForwardConfig *ForwardActionConfig `json:"forwardConfig,omitempty"`

	Order *int32 `json:"order,omitempty"`

	RedirectConfig *RedirectActionConfig `json:"redirectConfig,omitempty"`

	TargetGroupArn *string `json:"targetGroupArn,omitempty"`

	Type ActionTypeEnum `json:"type"`
}

// ActionOrder represents the ActionOrder type
type ActionOrder int32

// Actions represents the Actions type
type Actions []Action

// AddListenerCertificatesInput represents the AddListenerCertificatesInput structure
type AddListenerCertificatesInput struct {
	Certificates []Certificate `json:"certificates"`

	ListenerArn string `json:"listenerArn"`
}

// AddListenerCertificatesOutput represents the AddListenerCertificatesOutput structure
type AddListenerCertificatesOutput struct {
	Certificates []Certificate `json:"certificates,omitempty"`
}

// AddTagsInput represents the AddTagsInput structure
type AddTagsInput struct {
	ResourceArns []string `json:"resourceArns"`

	Tags []Tag `json:"tags"`
}

// AddTagsOutput represents the AddTagsOutput structure
type AddTagsOutput struct {
}

// AddTrustStoreRevocationsInput represents the AddTrustStoreRevocationsInput structure
type AddTrustStoreRevocationsInput struct {
	RevocationContents []RevocationContent `json:"revocationContents,omitempty"`

	TrustStoreArn string `json:"trustStoreArn"`
}

// AddTrustStoreRevocationsOutput represents the AddTrustStoreRevocationsOutput structure
type AddTrustStoreRevocationsOutput struct {
	TrustStoreRevocations []TrustStoreRevocation `json:"trustStoreRevocations,omitempty"`
}

// AdministrativeOverride represents the AdministrativeOverride structure
type AdministrativeOverride struct {
	Description *string `json:"description,omitempty"`

	Reason *TargetAdministrativeOverrideReasonEnum `json:"reason,omitempty"`

	State *TargetAdministrativeOverrideStateEnum `json:"state,omitempty"`
}

// AllocationId represents the AllocationId type
type AllocationId string

// AllocationIdNotFoundException represents the AllocationIdNotFoundException structure
type AllocationIdNotFoundException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for AllocationIdNotFoundException
func (e AllocationIdNotFoundException) Error() string {
	return "AllocationIdNotFoundException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e AllocationIdNotFoundException) ErrorCode() string {
	return "AllocationIdNotFoundException"
}

// ErrorFault indicates whether this is a client or server error
func (e AllocationIdNotFoundException) ErrorFault() string {
	return "client"
}

// AlpnPolicyName represents the AlpnPolicyName type
type AlpnPolicyName []string

// AlpnPolicyValue represents the AlpnPolicyValue type
type AlpnPolicyValue string

// AnomalyDetection represents the AnomalyDetection structure
type AnomalyDetection struct {
	MitigationInEffect *MitigationInEffectEnum `json:"mitigationInEffect,omitempty"`

	Result *AnomalyResultEnum `json:"result,omitempty"`
}

// AuthenticateCognitoActionAuthenticationRequestExtraParams represents the AuthenticateCognitoActionAuthenticationRequestExtraParams type
type AuthenticateCognitoActionAuthenticationRequestExtraParams map[string]string

// AuthenticateCognitoActionAuthenticationRequestParamName represents the AuthenticateCognitoActionAuthenticationRequestParamName type
type AuthenticateCognitoActionAuthenticationRequestParamName string

// AuthenticateCognitoActionAuthenticationRequestParamValue represents the AuthenticateCognitoActionAuthenticationRequestParamValue type
type AuthenticateCognitoActionAuthenticationRequestParamValue string

// AuthenticateCognitoActionConfig represents the AuthenticateCognitoActionConfig structure
type AuthenticateCognitoActionConfig struct {
	AuthenticationRequestExtraParams map[string]string `json:"authenticationRequestExtraParams,omitempty"`

	OnUnauthenticatedRequest *AuthenticateCognitoActionConditionalBehaviorEnum `json:"onUnauthenticatedRequest,omitempty"`

	Scope *string `json:"scope,omitempty"`

	SessionCookieName *string `json:"sessionCookieName,omitempty"`

	SessionTimeout *int64 `json:"sessionTimeout,omitempty"`

	UserPoolArn string `json:"userPoolArn"`

	UserPoolClientId string `json:"userPoolClientId"`

	UserPoolDomain string `json:"userPoolDomain"`
}

// AuthenticateCognitoActionScope represents the AuthenticateCognitoActionScope type
type AuthenticateCognitoActionScope string

// AuthenticateCognitoActionSessionCookieName represents the AuthenticateCognitoActionSessionCookieName type
type AuthenticateCognitoActionSessionCookieName string

// AuthenticateCognitoActionSessionTimeout represents the AuthenticateCognitoActionSessionTimeout type
type AuthenticateCognitoActionSessionTimeout int64

// AuthenticateCognitoActionUserPoolArn represents the AuthenticateCognitoActionUserPoolArn type
type AuthenticateCognitoActionUserPoolArn string

// AuthenticateCognitoActionUserPoolClientId represents the AuthenticateCognitoActionUserPoolClientId type
type AuthenticateCognitoActionUserPoolClientId string

// AuthenticateCognitoActionUserPoolDomain represents the AuthenticateCognitoActionUserPoolDomain type
type AuthenticateCognitoActionUserPoolDomain string

// AuthenticateOidcActionAuthenticationRequestExtraParams represents the AuthenticateOidcActionAuthenticationRequestExtraParams type
type AuthenticateOidcActionAuthenticationRequestExtraParams map[string]string

// AuthenticateOidcActionAuthenticationRequestParamName represents the AuthenticateOidcActionAuthenticationRequestParamName type
type AuthenticateOidcActionAuthenticationRequestParamName string

// AuthenticateOidcActionAuthenticationRequestParamValue represents the AuthenticateOidcActionAuthenticationRequestParamValue type
type AuthenticateOidcActionAuthenticationRequestParamValue string

// AuthenticateOidcActionAuthorizationEndpoint represents the AuthenticateOidcActionAuthorizationEndpoint type
type AuthenticateOidcActionAuthorizationEndpoint string

// AuthenticateOidcActionClientId represents the AuthenticateOidcActionClientId type
type AuthenticateOidcActionClientId string

// AuthenticateOidcActionClientSecret represents the AuthenticateOidcActionClientSecret type
type AuthenticateOidcActionClientSecret string

// AuthenticateOidcActionConfig represents the AuthenticateOidcActionConfig structure
type AuthenticateOidcActionConfig struct {
	AuthenticationRequestExtraParams map[string]string `json:"authenticationRequestExtraParams,omitempty"`

	AuthorizationEndpoint string `json:"authorizationEndpoint"`

	ClientId string `json:"clientId"`

	ClientSecret *string `json:"clientSecret,omitempty"`

	Issuer string `json:"issuer"`

	OnUnauthenticatedRequest *AuthenticateOidcActionConditionalBehaviorEnum `json:"onUnauthenticatedRequest,omitempty"`

	Scope *string `json:"scope,omitempty"`

	SessionCookieName *string `json:"sessionCookieName,omitempty"`

	SessionTimeout *int64 `json:"sessionTimeout,omitempty"`

	TokenEndpoint string `json:"tokenEndpoint"`

	UseExistingClientSecret *bool `json:"useExistingClientSecret,omitempty"`

	UserInfoEndpoint string `json:"userInfoEndpoint"`
}

// AuthenticateOidcActionIssuer represents the AuthenticateOidcActionIssuer type
type AuthenticateOidcActionIssuer string

// AuthenticateOidcActionScope represents the AuthenticateOidcActionScope type
type AuthenticateOidcActionScope string

// AuthenticateOidcActionSessionCookieName represents the AuthenticateOidcActionSessionCookieName type
type AuthenticateOidcActionSessionCookieName string

// AuthenticateOidcActionSessionTimeout represents the AuthenticateOidcActionSessionTimeout type
type AuthenticateOidcActionSessionTimeout int64

// AuthenticateOidcActionTokenEndpoint represents the AuthenticateOidcActionTokenEndpoint type
type AuthenticateOidcActionTokenEndpoint string

// AuthenticateOidcActionUseExistingClientSecret represents the AuthenticateOidcActionUseExistingClientSecret type
type AuthenticateOidcActionUseExistingClientSecret bool

// AuthenticateOidcActionUserInfoEndpoint represents the AuthenticateOidcActionUserInfoEndpoint type
type AuthenticateOidcActionUserInfoEndpoint string

// AvailabilityZone represents the AvailabilityZone structure
type AvailabilityZone struct {
	LoadBalancerAddresses []LoadBalancerAddress `json:"loadBalancerAddresses,omitempty"`

	OutpostId *string `json:"outpostId,omitempty"`

	SourceNatIpv6Prefixes []string `json:"sourceNatIpv6Prefixes,omitempty"`

	SubnetId *string `json:"subnetId,omitempty"`

	ZoneName *string `json:"zoneName,omitempty"`
}

// AvailabilityZoneNotSupportedException represents the AvailabilityZoneNotSupportedException structure
type AvailabilityZoneNotSupportedException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for AvailabilityZoneNotSupportedException
func (e AvailabilityZoneNotSupportedException) Error() string {
	return "AvailabilityZoneNotSupportedException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e AvailabilityZoneNotSupportedException) ErrorCode() string {
	return "AvailabilityZoneNotSupportedException"
}

// ErrorFault indicates whether this is a client or server error
func (e AvailabilityZoneNotSupportedException) ErrorFault() string {
	return "client"
}

// AvailabilityZones represents the AvailabilityZones type
type AvailabilityZones []AvailabilityZone

// CaCertificatesBundleNotFoundException represents the CaCertificatesBundleNotFoundException structure
type CaCertificatesBundleNotFoundException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for CaCertificatesBundleNotFoundException
func (e CaCertificatesBundleNotFoundException) Error() string {
	return "CaCertificatesBundleNotFoundException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e CaCertificatesBundleNotFoundException) ErrorCode() string {
	return "CaCertificatesBundleNotFoundException"
}

// ErrorFault indicates whether this is a client or server error
func (e CaCertificatesBundleNotFoundException) ErrorFault() string {
	return "client"
}

// CanonicalHostedZoneId represents the CanonicalHostedZoneId type
type CanonicalHostedZoneId string

// CapacityDecreaseRequestsLimitExceededException represents the CapacityDecreaseRequestsLimitExceededException structure
type CapacityDecreaseRequestsLimitExceededException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for CapacityDecreaseRequestsLimitExceededException
func (e CapacityDecreaseRequestsLimitExceededException) Error() string {
	return "CapacityDecreaseRequestsLimitExceededException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e CapacityDecreaseRequestsLimitExceededException) ErrorCode() string {
	return "CapacityDecreaseRequestsLimitExceededException"
}

// ErrorFault indicates whether this is a client or server error
func (e CapacityDecreaseRequestsLimitExceededException) ErrorFault() string {
	return "client"
}

// CapacityReservationPendingException represents the CapacityReservationPendingException structure
type CapacityReservationPendingException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for CapacityReservationPendingException
func (e CapacityReservationPendingException) Error() string {
	return "CapacityReservationPendingException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e CapacityReservationPendingException) ErrorCode() string {
	return "CapacityReservationPendingException"
}

// ErrorFault indicates whether this is a client or server error
func (e CapacityReservationPendingException) ErrorFault() string {
	return "client"
}

// CapacityReservationStatus represents the CapacityReservationStatus structure
type CapacityReservationStatus struct {
	Code *CapacityReservationStateEnum `json:"code,omitempty"`

	Reason *string `json:"reason,omitempty"`
}

// CapacityUnits represents the CapacityUnits type
type CapacityUnits int32

// CapacityUnitsDouble represents the CapacityUnitsDouble type
type CapacityUnitsDouble float64

// CapacityUnitsLimitExceededException represents the CapacityUnitsLimitExceededException structure
type CapacityUnitsLimitExceededException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for CapacityUnitsLimitExceededException
func (e CapacityUnitsLimitExceededException) Error() string {
	return "CapacityUnitsLimitExceededException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e CapacityUnitsLimitExceededException) ErrorCode() string {
	return "CapacityUnitsLimitExceededException"
}

// ErrorFault indicates whether this is a client or server error
func (e CapacityUnitsLimitExceededException) ErrorFault() string {
	return "client"
}

// Certificate represents the Certificate structure
type Certificate struct {
	CertificateArn *string `json:"certificateArn,omitempty"`

	IsDefault *bool `json:"isDefault,omitempty"`
}

// CertificateArn represents the CertificateArn type
type CertificateArn string

// CertificateList represents the CertificateList type
type CertificateList []Certificate

// CertificateNotFoundException represents the CertificateNotFoundException structure
type CertificateNotFoundException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for CertificateNotFoundException
func (e CertificateNotFoundException) Error() string {
	return "CertificateNotFoundException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e CertificateNotFoundException) ErrorCode() string {
	return "CertificateNotFoundException"
}

// ErrorFault indicates whether this is a client or server error
func (e CertificateNotFoundException) ErrorFault() string {
	return "client"
}

// Cipher represents the Cipher structure
type Cipher struct {
	Name *string `json:"name,omitempty"`

	Priority *int32 `json:"priority,omitempty"`
}

// CipherName represents the CipherName type
type CipherName string

// CipherPriority represents the CipherPriority type
type CipherPriority int32

// Ciphers represents the Ciphers type
type Ciphers []Cipher

// ConditionFieldName represents the ConditionFieldName type
type ConditionFieldName string

// CreateListenerInput represents the CreateListenerInput structure
type CreateListenerInput struct {
	AlpnPolicy []string `json:"alpnPolicy,omitempty"`

	Certificates []Certificate `json:"certificates,omitempty"`

	DefaultActions []Action `json:"defaultActions"`

	LoadBalancerArn string `json:"loadBalancerArn"`

	MutualAuthentication *MutualAuthenticationAttributes `json:"mutualAuthentication,omitempty"`

	Port *int32 `json:"port,omitempty"`

	Protocol *ProtocolEnum `json:"protocol,omitempty"`

	SslPolicy *string `json:"sslPolicy,omitempty"`

	Tags []Tag `json:"tags,omitempty"`
}

// CreateListenerOutput represents the CreateListenerOutput structure
type CreateListenerOutput struct {
	Listeners []Listener `json:"listeners,omitempty"`
}

// CreateLoadBalancerInput represents the CreateLoadBalancerInput structure
type CreateLoadBalancerInput struct {
	CustomerOwnedIpv4Pool *string `json:"customerOwnedIpv4Pool,omitempty"`

	EnablePrefixForIpv6SourceNat *EnablePrefixForIpv6SourceNatEnum `json:"enablePrefixForIpv6SourceNat,omitempty"`

	IpAddressType *IpAddressType `json:"ipAddressType,omitempty"`

	IpamPools *IpamPools `json:"ipamPools,omitempty"`

	Name string `json:"name"`

	Scheme *LoadBalancerSchemeEnum `json:"scheme,omitempty"`

	SecurityGroups []string `json:"securityGroups,omitempty"`

	SubnetMappings []SubnetMapping `json:"subnetMappings,omitempty"`

	Subnets []string `json:"subnets,omitempty"`

	Tags []Tag `json:"tags,omitempty"`

	Type *LoadBalancerTypeEnum `json:"type,omitempty"`
}

// CreateLoadBalancerOutput represents the CreateLoadBalancerOutput structure
type CreateLoadBalancerOutput struct {
	LoadBalancers []LoadBalancer `json:"loadBalancers,omitempty"`
}

// CreateRuleInput represents the CreateRuleInput structure
type CreateRuleInput struct {
	Actions []Action `json:"actions"`

	Conditions []RuleCondition `json:"conditions"`

	ListenerArn string `json:"listenerArn"`

	Priority int32 `json:"priority"`

	Tags []Tag `json:"tags,omitempty"`
}

// CreateRuleOutput represents the CreateRuleOutput structure
type CreateRuleOutput struct {
	Rules []Rule `json:"rules,omitempty"`
}

// CreateTargetGroupInput represents the CreateTargetGroupInput structure
type CreateTargetGroupInput struct {
	HealthCheckEnabled *bool `json:"healthCheckEnabled,omitempty"`

	HealthCheckIntervalSeconds *int32 `json:"healthCheckIntervalSeconds,omitempty"`

	HealthCheckPath *string `json:"healthCheckPath,omitempty"`

	HealthCheckPort *string `json:"healthCheckPort,omitempty"`

	HealthCheckProtocol *ProtocolEnum `json:"healthCheckProtocol,omitempty"`

	HealthCheckTimeoutSeconds *int32 `json:"healthCheckTimeoutSeconds,omitempty"`

	HealthyThresholdCount *int32 `json:"healthyThresholdCount,omitempty"`

	IpAddressType *TargetGroupIpAddressTypeEnum `json:"ipAddressType,omitempty"`

	Matcher *Matcher `json:"matcher,omitempty"`

	Name string `json:"name"`

	Port *int32 `json:"port,omitempty"`

	Protocol *ProtocolEnum `json:"protocol,omitempty"`

	ProtocolVersion *string `json:"protocolVersion,omitempty"`

	Tags []Tag `json:"tags,omitempty"`

	TargetType *TargetTypeEnum `json:"targetType,omitempty"`

	UnhealthyThresholdCount *int32 `json:"unhealthyThresholdCount,omitempty"`

	VpcId *string `json:"vpcId,omitempty"`
}

// CreateTargetGroupOutput represents the CreateTargetGroupOutput structure
type CreateTargetGroupOutput struct {
	TargetGroups []TargetGroup `json:"targetGroups,omitempty"`
}

// CreateTrustStoreInput represents the CreateTrustStoreInput structure
type CreateTrustStoreInput struct {
	CaCertificatesBundleS3Bucket string `json:"caCertificatesBundleS3Bucket"`

	CaCertificatesBundleS3Key string `json:"caCertificatesBundleS3Key"`

	CaCertificatesBundleS3ObjectVersion *string `json:"caCertificatesBundleS3ObjectVersion,omitempty"`

	Name string `json:"name"`

	Tags []Tag `json:"tags,omitempty"`
}

// CreateTrustStoreOutput represents the CreateTrustStoreOutput structure
type CreateTrustStoreOutput struct {
	TrustStores []TrustStore `json:"trustStores,omitempty"`
}

// CreatedTime represents the CreatedTime type
type CreatedTime time.Time

// CustomerOwnedIpv4Pool represents the CustomerOwnedIpv4Pool type
type CustomerOwnedIpv4Pool string

// DNSName represents the DNSName type
type DNSName string

// DecreaseRequestsRemaining represents the DecreaseRequestsRemaining type
type DecreaseRequestsRemaining int32

// Default represents the Default type
type Default bool

// DeleteAssociationSameAccountException represents the DeleteAssociationSameAccountException structure
type DeleteAssociationSameAccountException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for DeleteAssociationSameAccountException
func (e DeleteAssociationSameAccountException) Error() string {
	return "DeleteAssociationSameAccountException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e DeleteAssociationSameAccountException) ErrorCode() string {
	return "DeleteAssociationSameAccountException"
}

// ErrorFault indicates whether this is a client or server error
func (e DeleteAssociationSameAccountException) ErrorFault() string {
	return "client"
}

// DeleteListenerInput represents the DeleteListenerInput structure
type DeleteListenerInput struct {
	ListenerArn string `json:"listenerArn"`
}

// DeleteListenerOutput represents the DeleteListenerOutput structure
type DeleteListenerOutput struct {
}

// DeleteLoadBalancerInput represents the DeleteLoadBalancerInput structure
type DeleteLoadBalancerInput struct {
	LoadBalancerArn string `json:"loadBalancerArn"`
}

// DeleteLoadBalancerOutput represents the DeleteLoadBalancerOutput structure
type DeleteLoadBalancerOutput struct {
}

// DeleteRuleInput represents the DeleteRuleInput structure
type DeleteRuleInput struct {
	RuleArn string `json:"ruleArn"`
}

// DeleteRuleOutput represents the DeleteRuleOutput structure
type DeleteRuleOutput struct {
}

// DeleteSharedTrustStoreAssociationInput represents the DeleteSharedTrustStoreAssociationInput structure
type DeleteSharedTrustStoreAssociationInput struct {
	ResourceArn string `json:"resourceArn"`

	TrustStoreArn string `json:"trustStoreArn"`
}

// DeleteSharedTrustStoreAssociationOutput represents the DeleteSharedTrustStoreAssociationOutput structure
type DeleteSharedTrustStoreAssociationOutput struct {
}

// DeleteTargetGroupInput represents the DeleteTargetGroupInput structure
type DeleteTargetGroupInput struct {
	TargetGroupArn string `json:"targetGroupArn"`
}

// DeleteTargetGroupOutput represents the DeleteTargetGroupOutput structure
type DeleteTargetGroupOutput struct {
}

// DeleteTrustStoreInput represents the DeleteTrustStoreInput structure
type DeleteTrustStoreInput struct {
	TrustStoreArn string `json:"trustStoreArn"`
}

// DeleteTrustStoreOutput represents the DeleteTrustStoreOutput structure
type DeleteTrustStoreOutput struct {
}

// DeregisterTargetsInput represents the DeregisterTargetsInput structure
type DeregisterTargetsInput struct {
	TargetGroupArn string `json:"targetGroupArn"`

	Targets []TargetDescription `json:"targets"`
}

// DeregisterTargetsOutput represents the DeregisterTargetsOutput structure
type DeregisterTargetsOutput struct {
}

// DescribeAccountLimitsInput represents the DescribeAccountLimitsInput structure
type DescribeAccountLimitsInput struct {
	Marker *string `json:"marker,omitempty"`

	PageSize *int32 `json:"pageSize,omitempty"`
}

// DescribeAccountLimitsOutput represents the DescribeAccountLimitsOutput structure
type DescribeAccountLimitsOutput struct {
	Limits []Limit `json:"limits,omitempty"`

	NextMarker *string `json:"nextMarker,omitempty"`
}

// DescribeCapacityReservationInput represents the DescribeCapacityReservationInput structure
type DescribeCapacityReservationInput struct {
	LoadBalancerArn string `json:"loadBalancerArn"`
}

// DescribeCapacityReservationOutput represents the DescribeCapacityReservationOutput structure
type DescribeCapacityReservationOutput struct {
	CapacityReservationState []ZonalCapacityReservationState `json:"capacityReservationState,omitempty"`

	DecreaseRequestsRemaining *int32 `json:"decreaseRequestsRemaining,omitempty"`

	LastModifiedTime *time.Time `json:"lastModifiedTime,omitempty"`

	MinimumLoadBalancerCapacity *MinimumLoadBalancerCapacity `json:"minimumLoadBalancerCapacity,omitempty"`
}

// DescribeListenerAttributesInput represents the DescribeListenerAttributesInput structure
type DescribeListenerAttributesInput struct {
	ListenerArn string `json:"listenerArn"`
}

// DescribeListenerAttributesOutput represents the DescribeListenerAttributesOutput structure
type DescribeListenerAttributesOutput struct {
	Attributes []ListenerAttribute `json:"attributes,omitempty"`
}

// DescribeListenerCertificatesInput represents the DescribeListenerCertificatesInput structure
type DescribeListenerCertificatesInput struct {
	ListenerArn string `json:"listenerArn"`

	Marker *string `json:"marker,omitempty"`

	PageSize *int32 `json:"pageSize,omitempty"`
}

// DescribeListenerCertificatesOutput represents the DescribeListenerCertificatesOutput structure
type DescribeListenerCertificatesOutput struct {
	Certificates []Certificate `json:"certificates,omitempty"`

	NextMarker *string `json:"nextMarker,omitempty"`
}

// DescribeListenersInput represents the DescribeListenersInput structure
type DescribeListenersInput struct {
	ListenerArns []string `json:"listenerArns,omitempty"`

	LoadBalancerArn *string `json:"loadBalancerArn,omitempty"`

	Marker *string `json:"marker,omitempty"`

	PageSize *int32 `json:"pageSize,omitempty"`
}

// DescribeListenersOutput represents the DescribeListenersOutput structure
type DescribeListenersOutput struct {
	Listeners []Listener `json:"listeners,omitempty"`

	NextMarker *string `json:"nextMarker,omitempty"`
}

// DescribeLoadBalancerAttributesInput represents the DescribeLoadBalancerAttributesInput structure
type DescribeLoadBalancerAttributesInput struct {
	LoadBalancerArn string `json:"loadBalancerArn"`
}

// DescribeLoadBalancerAttributesOutput represents the DescribeLoadBalancerAttributesOutput structure
type DescribeLoadBalancerAttributesOutput struct {
	Attributes []LoadBalancerAttribute `json:"attributes,omitempty"`
}

// DescribeLoadBalancersInput represents the DescribeLoadBalancersInput structure
type DescribeLoadBalancersInput struct {
	LoadBalancerArns []string `json:"loadBalancerArns,omitempty"`

	Marker *string `json:"marker,omitempty"`

	Names []string `json:"names,omitempty"`

	PageSize *int32 `json:"pageSize,omitempty"`
}

// DescribeLoadBalancersOutput represents the DescribeLoadBalancersOutput structure
type DescribeLoadBalancersOutput struct {
	LoadBalancers []LoadBalancer `json:"loadBalancers,omitempty"`

	NextMarker *string `json:"nextMarker,omitempty"`
}

// DescribeRulesInput represents the DescribeRulesInput structure
type DescribeRulesInput struct {
	ListenerArn *string `json:"listenerArn,omitempty"`

	Marker *string `json:"marker,omitempty"`

	PageSize *int32 `json:"pageSize,omitempty"`

	RuleArns []string `json:"ruleArns,omitempty"`
}

// DescribeRulesOutput represents the DescribeRulesOutput structure
type DescribeRulesOutput struct {
	NextMarker *string `json:"nextMarker,omitempty"`

	Rules []Rule `json:"rules,omitempty"`
}

// DescribeSSLPoliciesInput represents the DescribeSSLPoliciesInput structure
type DescribeSSLPoliciesInput struct {
	LoadBalancerType *LoadBalancerTypeEnum `json:"loadBalancerType,omitempty"`

	Marker *string `json:"marker,omitempty"`

	Names []string `json:"names,omitempty"`

	PageSize *int32 `json:"pageSize,omitempty"`
}

// DescribeSSLPoliciesOutput represents the DescribeSSLPoliciesOutput structure
type DescribeSSLPoliciesOutput struct {
	NextMarker *string `json:"nextMarker,omitempty"`

	SslPolicies []SslPolicy `json:"sslPolicies,omitempty"`
}

// DescribeTagsInput represents the DescribeTagsInput structure
type DescribeTagsInput struct {
	ResourceArns []string `json:"resourceArns"`
}

// DescribeTagsOutput represents the DescribeTagsOutput structure
type DescribeTagsOutput struct {
	TagDescriptions []TagDescription `json:"tagDescriptions,omitempty"`
}

// DescribeTargetGroupAttributesInput represents the DescribeTargetGroupAttributesInput structure
type DescribeTargetGroupAttributesInput struct {
	TargetGroupArn string `json:"targetGroupArn"`
}

// DescribeTargetGroupAttributesOutput represents the DescribeTargetGroupAttributesOutput structure
type DescribeTargetGroupAttributesOutput struct {
	Attributes []TargetGroupAttribute `json:"attributes,omitempty"`
}

// DescribeTargetGroupsInput represents the DescribeTargetGroupsInput structure
type DescribeTargetGroupsInput struct {
	LoadBalancerArn *string `json:"loadBalancerArn,omitempty"`

	Marker *string `json:"marker,omitempty"`

	Names []string `json:"names,omitempty"`

	PageSize *int32 `json:"pageSize,omitempty"`

	TargetGroupArns []string `json:"targetGroupArns,omitempty"`
}

// DescribeTargetGroupsOutput represents the DescribeTargetGroupsOutput structure
type DescribeTargetGroupsOutput struct {
	NextMarker *string `json:"nextMarker,omitempty"`

	TargetGroups []TargetGroup `json:"targetGroups,omitempty"`
}

// DescribeTargetHealthInput represents the DescribeTargetHealthInput structure
type DescribeTargetHealthInput struct {
	Include []DescribeTargetHealthInputIncludeEnum `json:"include,omitempty"`

	TargetGroupArn string `json:"targetGroupArn"`

	Targets []TargetDescription `json:"targets,omitempty"`
}

// DescribeTargetHealthOutput represents the DescribeTargetHealthOutput structure
type DescribeTargetHealthOutput struct {
	TargetHealthDescriptions []TargetHealthDescription `json:"targetHealthDescriptions,omitempty"`
}

// DescribeTrustStoreAssociationsInput represents the DescribeTrustStoreAssociationsInput structure
type DescribeTrustStoreAssociationsInput struct {
	Marker *string `json:"marker,omitempty"`

	PageSize *int32 `json:"pageSize,omitempty"`

	TrustStoreArn string `json:"trustStoreArn"`
}

// DescribeTrustStoreAssociationsOutput represents the DescribeTrustStoreAssociationsOutput structure
type DescribeTrustStoreAssociationsOutput struct {
	NextMarker *string `json:"nextMarker,omitempty"`

	TrustStoreAssociations []TrustStoreAssociation `json:"trustStoreAssociations,omitempty"`
}

// DescribeTrustStoreRevocation represents the DescribeTrustStoreRevocation structure
type DescribeTrustStoreRevocation struct {
	NumberOfRevokedEntries *int64 `json:"numberOfRevokedEntries,omitempty"`

	RevocationId *int64 `json:"revocationId,omitempty"`

	RevocationType *RevocationType `json:"revocationType,omitempty"`

	TrustStoreArn *string `json:"trustStoreArn,omitempty"`
}

// DescribeTrustStoreRevocationResponse represents the DescribeTrustStoreRevocationResponse type
type DescribeTrustStoreRevocationResponse []DescribeTrustStoreRevocation

// DescribeTrustStoreRevocationsInput represents the DescribeTrustStoreRevocationsInput structure
type DescribeTrustStoreRevocationsInput struct {
	Marker *string `json:"marker,omitempty"`

	PageSize *int32 `json:"pageSize,omitempty"`

	RevocationIds []int64 `json:"revocationIds,omitempty"`

	TrustStoreArn string `json:"trustStoreArn"`
}

// DescribeTrustStoreRevocationsOutput represents the DescribeTrustStoreRevocationsOutput structure
type DescribeTrustStoreRevocationsOutput struct {
	NextMarker *string `json:"nextMarker,omitempty"`

	TrustStoreRevocations []DescribeTrustStoreRevocation `json:"trustStoreRevocations,omitempty"`
}

// DescribeTrustStoresInput represents the DescribeTrustStoresInput structure
type DescribeTrustStoresInput struct {
	Marker *string `json:"marker,omitempty"`

	Names []string `json:"names,omitempty"`

	PageSize *int32 `json:"pageSize,omitempty"`

	TrustStoreArns []string `json:"trustStoreArns,omitempty"`
}

// DescribeTrustStoresOutput represents the DescribeTrustStoresOutput structure
type DescribeTrustStoresOutput struct {
	NextMarker *string `json:"nextMarker,omitempty"`

	TrustStores []TrustStore `json:"trustStores,omitempty"`
}

// Description represents the Description type
type Description string

// DuplicateListenerException represents the DuplicateListenerException structure
type DuplicateListenerException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for DuplicateListenerException
func (e DuplicateListenerException) Error() string {
	return "DuplicateListenerException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e DuplicateListenerException) ErrorCode() string {
	return "DuplicateListenerException"
}

// ErrorFault indicates whether this is a client or server error
func (e DuplicateListenerException) ErrorFault() string {
	return "client"
}

// DuplicateLoadBalancerNameException represents the DuplicateLoadBalancerNameException structure
type DuplicateLoadBalancerNameException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for DuplicateLoadBalancerNameException
func (e DuplicateLoadBalancerNameException) Error() string {
	return "DuplicateLoadBalancerNameException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e DuplicateLoadBalancerNameException) ErrorCode() string {
	return "DuplicateLoadBalancerNameException"
}

// ErrorFault indicates whether this is a client or server error
func (e DuplicateLoadBalancerNameException) ErrorFault() string {
	return "client"
}

// DuplicateTagKeysException represents the DuplicateTagKeysException structure
type DuplicateTagKeysException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for DuplicateTagKeysException
func (e DuplicateTagKeysException) Error() string {
	return "DuplicateTagKeysException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e DuplicateTagKeysException) ErrorCode() string {
	return "DuplicateTagKeysException"
}

// ErrorFault indicates whether this is a client or server error
func (e DuplicateTagKeysException) ErrorFault() string {
	return "client"
}

// DuplicateTargetGroupNameException represents the DuplicateTargetGroupNameException structure
type DuplicateTargetGroupNameException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for DuplicateTargetGroupNameException
func (e DuplicateTargetGroupNameException) Error() string {
	return "DuplicateTargetGroupNameException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e DuplicateTargetGroupNameException) ErrorCode() string {
	return "DuplicateTargetGroupNameException"
}

// ErrorFault indicates whether this is a client or server error
func (e DuplicateTargetGroupNameException) ErrorFault() string {
	return "client"
}

// DuplicateTrustStoreNameException represents the DuplicateTrustStoreNameException structure
type DuplicateTrustStoreNameException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for DuplicateTrustStoreNameException
func (e DuplicateTrustStoreNameException) Error() string {
	return "DuplicateTrustStoreNameException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e DuplicateTrustStoreNameException) ErrorCode() string {
	return "DuplicateTrustStoreNameException"
}

// ErrorFault indicates whether this is a client or server error
func (e DuplicateTrustStoreNameException) ErrorFault() string {
	return "client"
}

// EnforceSecurityGroupInboundRulesOnPrivateLinkTraffic represents the EnforceSecurityGroupInboundRulesOnPrivateLinkTraffic type
type EnforceSecurityGroupInboundRulesOnPrivateLinkTraffic string

// ErrorDescription represents the ErrorDescription type
type ErrorDescription string

// FixedResponseActionConfig represents the FixedResponseActionConfig structure
type FixedResponseActionConfig struct {
	ContentType *string `json:"contentType,omitempty"`

	MessageBody *string `json:"messageBody,omitempty"`

	StatusCode string `json:"statusCode"`
}

// FixedResponseActionContentType represents the FixedResponseActionContentType type
type FixedResponseActionContentType string

// FixedResponseActionMessage represents the FixedResponseActionMessage type
type FixedResponseActionMessage string

// FixedResponseActionStatusCode represents the FixedResponseActionStatusCode type
type FixedResponseActionStatusCode string

// ForwardActionConfig represents the ForwardActionConfig structure
type ForwardActionConfig struct {
	TargetGroupStickinessConfig *TargetGroupStickinessConfig `json:"targetGroupStickinessConfig,omitempty"`

	TargetGroups []TargetGroupTuple `json:"targetGroups,omitempty"`
}

// GetResourcePolicyInput represents the GetResourcePolicyInput structure
type GetResourcePolicyInput struct {
	ResourceArn string `json:"resourceArn"`
}

// GetResourcePolicyOutput represents the GetResourcePolicyOutput structure
type GetResourcePolicyOutput struct {
	Policy *string `json:"policy,omitempty"`
}

// GetTrustStoreCaCertificatesBundleInput represents the GetTrustStoreCaCertificatesBundleInput structure
type GetTrustStoreCaCertificatesBundleInput struct {
	TrustStoreArn string `json:"trustStoreArn"`
}

// GetTrustStoreCaCertificatesBundleOutput represents the GetTrustStoreCaCertificatesBundleOutput structure
type GetTrustStoreCaCertificatesBundleOutput struct {
	Location *string `json:"location,omitempty"`
}

// GetTrustStoreRevocationContentInput represents the GetTrustStoreRevocationContentInput structure
type GetTrustStoreRevocationContentInput struct {
	RevocationId int64 `json:"revocationId"`

	TrustStoreArn string `json:"trustStoreArn"`
}

// GetTrustStoreRevocationContentOutput represents the GetTrustStoreRevocationContentOutput structure
type GetTrustStoreRevocationContentOutput struct {
	Location *string `json:"location,omitempty"`
}

// GrpcCode represents the GrpcCode type
type GrpcCode string

// HealthCheckEnabled represents the HealthCheckEnabled type
type HealthCheckEnabled bool

// HealthCheckIntervalSeconds represents the HealthCheckIntervalSeconds type
type HealthCheckIntervalSeconds int32

// HealthCheckPort represents the HealthCheckPort type
type HealthCheckPort string

// HealthCheckThresholdCount represents the HealthCheckThresholdCount type
type HealthCheckThresholdCount int32

// HealthCheckTimeoutSeconds represents the HealthCheckTimeoutSeconds type
type HealthCheckTimeoutSeconds int32

// HealthUnavailableException represents the HealthUnavailableException structure
type HealthUnavailableException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for HealthUnavailableException
func (e HealthUnavailableException) Error() string {
	return "HealthUnavailableException: AWS server error (HTTP 500)"
}

// ErrorCode returns the AWS error code
func (e HealthUnavailableException) ErrorCode() string {
	return "HealthUnavailableException"
}

// ErrorFault indicates whether this is a client or server error
func (e HealthUnavailableException) ErrorFault() string {
	return "server"
}

// HostHeaderConditionConfig represents the HostHeaderConditionConfig structure
type HostHeaderConditionConfig struct {
	Values []string `json:"values,omitempty"`
}

// HttpCode represents the HttpCode type
type HttpCode string

// HttpHeaderConditionConfig represents the HttpHeaderConditionConfig structure
type HttpHeaderConditionConfig struct {
	HttpHeaderName *string `json:"httpHeaderName,omitempty"`

	Values []string `json:"values,omitempty"`
}

// HttpHeaderConditionName represents the HttpHeaderConditionName type
type HttpHeaderConditionName string

// HttpRequestMethodConditionConfig represents the HttpRequestMethodConditionConfig structure
type HttpRequestMethodConditionConfig struct {
	Values []string `json:"values,omitempty"`
}

// IPv6Address represents the IPv6Address type
type IPv6Address string

// IgnoreClientCertificateExpiry represents the IgnoreClientCertificateExpiry type
type IgnoreClientCertificateExpiry bool

// IncompatibleProtocolsException represents the IncompatibleProtocolsException structure
type IncompatibleProtocolsException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for IncompatibleProtocolsException
func (e IncompatibleProtocolsException) Error() string {
	return "IncompatibleProtocolsException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e IncompatibleProtocolsException) ErrorCode() string {
	return "IncompatibleProtocolsException"
}

// ErrorFault indicates whether this is a client or server error
func (e IncompatibleProtocolsException) ErrorFault() string {
	return "client"
}

// InsufficientCapacityException represents the InsufficientCapacityException structure
type InsufficientCapacityException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for InsufficientCapacityException
func (e InsufficientCapacityException) Error() string {
	return "InsufficientCapacityException: AWS server error (HTTP 500)"
}

// ErrorCode returns the AWS error code
func (e InsufficientCapacityException) ErrorCode() string {
	return "InsufficientCapacityException"
}

// ErrorFault indicates whether this is a client or server error
func (e InsufficientCapacityException) ErrorFault() string {
	return "server"
}

// InvalidCaCertificatesBundleException represents the InvalidCaCertificatesBundleException structure
type InvalidCaCertificatesBundleException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for InvalidCaCertificatesBundleException
func (e InvalidCaCertificatesBundleException) Error() string {
	return "InvalidCaCertificatesBundleException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e InvalidCaCertificatesBundleException) ErrorCode() string {
	return "InvalidCaCertificatesBundleException"
}

// ErrorFault indicates whether this is a client or server error
func (e InvalidCaCertificatesBundleException) ErrorFault() string {
	return "client"
}

// InvalidConfigurationRequestException represents the InvalidConfigurationRequestException structure
type InvalidConfigurationRequestException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for InvalidConfigurationRequestException
func (e InvalidConfigurationRequestException) Error() string {
	return "InvalidConfigurationRequestException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e InvalidConfigurationRequestException) ErrorCode() string {
	return "InvalidConfigurationRequestException"
}

// ErrorFault indicates whether this is a client or server error
func (e InvalidConfigurationRequestException) ErrorFault() string {
	return "client"
}

// InvalidLoadBalancerActionException represents the InvalidLoadBalancerActionException structure
type InvalidLoadBalancerActionException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for InvalidLoadBalancerActionException
func (e InvalidLoadBalancerActionException) Error() string {
	return "InvalidLoadBalancerActionException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e InvalidLoadBalancerActionException) ErrorCode() string {
	return "InvalidLoadBalancerActionException"
}

// ErrorFault indicates whether this is a client or server error
func (e InvalidLoadBalancerActionException) ErrorFault() string {
	return "client"
}

// InvalidRevocationContentException represents the InvalidRevocationContentException structure
type InvalidRevocationContentException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for InvalidRevocationContentException
func (e InvalidRevocationContentException) Error() string {
	return "InvalidRevocationContentException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e InvalidRevocationContentException) ErrorCode() string {
	return "InvalidRevocationContentException"
}

// ErrorFault indicates whether this is a client or server error
func (e InvalidRevocationContentException) ErrorFault() string {
	return "client"
}

// InvalidSchemeException represents the InvalidSchemeException structure
type InvalidSchemeException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for InvalidSchemeException
func (e InvalidSchemeException) Error() string {
	return "InvalidSchemeException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e InvalidSchemeException) ErrorCode() string {
	return "InvalidSchemeException"
}

// ErrorFault indicates whether this is a client or server error
func (e InvalidSchemeException) ErrorFault() string {
	return "client"
}

// InvalidSecurityGroupException represents the InvalidSecurityGroupException structure
type InvalidSecurityGroupException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for InvalidSecurityGroupException
func (e InvalidSecurityGroupException) Error() string {
	return "InvalidSecurityGroupException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e InvalidSecurityGroupException) ErrorCode() string {
	return "InvalidSecurityGroupException"
}

// ErrorFault indicates whether this is a client or server error
func (e InvalidSecurityGroupException) ErrorFault() string {
	return "client"
}

// InvalidSubnetException represents the InvalidSubnetException structure
type InvalidSubnetException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for InvalidSubnetException
func (e InvalidSubnetException) Error() string {
	return "InvalidSubnetException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e InvalidSubnetException) ErrorCode() string {
	return "InvalidSubnetException"
}

// ErrorFault indicates whether this is a client or server error
func (e InvalidSubnetException) ErrorFault() string {
	return "client"
}

// InvalidTargetException represents the InvalidTargetException structure
type InvalidTargetException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for InvalidTargetException
func (e InvalidTargetException) Error() string {
	return "InvalidTargetException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e InvalidTargetException) ErrorCode() string {
	return "InvalidTargetException"
}

// ErrorFault indicates whether this is a client or server error
func (e InvalidTargetException) ErrorFault() string {
	return "client"
}

// IpAddress represents the IpAddress type
type IpAddress string

// IpamPoolId represents the IpamPoolId type
type IpamPoolId string

// IpamPools represents the IpamPools structure
type IpamPools struct {
	Ipv4IpamPoolId *string `json:"ipv4IpamPoolId,omitempty"`
}

// IsDefault represents the IsDefault type
type IsDefault bool

// LastModifiedTime represents the LastModifiedTime type
type LastModifiedTime time.Time

// Limit represents the Limit structure
type Limit struct {
	Max *string `json:"max,omitempty"`

	Name *string `json:"name,omitempty"`
}

// Limits represents the Limits type
type Limits []Limit

// ListOfDescribeTargetHealthIncludeOptions represents the ListOfDescribeTargetHealthIncludeOptions type
type ListOfDescribeTargetHealthIncludeOptions []DescribeTargetHealthInputIncludeEnum

// ListOfString represents the ListOfString type
type ListOfString []string

// Listener represents the Listener structure
type Listener struct {
	AlpnPolicy []string `json:"alpnPolicy,omitempty"`

	Certificates []Certificate `json:"certificates,omitempty"`

	DefaultActions []Action `json:"defaultActions,omitempty"`

	ListenerArn *string `json:"listenerArn,omitempty"`

	LoadBalancerArn *string `json:"loadBalancerArn,omitempty"`

	MutualAuthentication *MutualAuthenticationAttributes `json:"mutualAuthentication,omitempty"`

	Port *int32 `json:"port,omitempty"`

	Protocol *ProtocolEnum `json:"protocol,omitempty"`

	SslPolicy *string `json:"sslPolicy,omitempty"`
}

// ListenerArn represents the ListenerArn type
type ListenerArn string

// ListenerArns represents the ListenerArns type
type ListenerArns []string

// ListenerAttribute represents the ListenerAttribute structure
type ListenerAttribute struct {
	Key *string `json:"key,omitempty"`

	Value *string `json:"value,omitempty"`
}

// ListenerAttributeKey represents the ListenerAttributeKey type
type ListenerAttributeKey string

// ListenerAttributeValue represents the ListenerAttributeValue type
type ListenerAttributeValue string

// ListenerAttributes represents the ListenerAttributes type
type ListenerAttributes []ListenerAttribute

// ListenerNotFoundException represents the ListenerNotFoundException structure
type ListenerNotFoundException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for ListenerNotFoundException
func (e ListenerNotFoundException) Error() string {
	return "ListenerNotFoundException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e ListenerNotFoundException) ErrorCode() string {
	return "ListenerNotFoundException"
}

// ErrorFault indicates whether this is a client or server error
func (e ListenerNotFoundException) ErrorFault() string {
	return "client"
}

// Listeners represents the Listeners type
type Listeners []Listener

// LoadBalancer represents the LoadBalancer structure
type LoadBalancer struct {
	AvailabilityZones []AvailabilityZone `json:"availabilityZones,omitempty"`

	CanonicalHostedZoneId *string `json:"canonicalHostedZoneId,omitempty"`

	CreatedTime *time.Time `json:"createdTime,omitempty"`

	CustomerOwnedIpv4Pool *string `json:"customerOwnedIpv4Pool,omitempty"`

	DNSName *string `json:"dNSName,omitempty"`

	EnablePrefixForIpv6SourceNat *EnablePrefixForIpv6SourceNatEnum `json:"enablePrefixForIpv6SourceNat,omitempty"`

	EnforceSecurityGroupInboundRulesOnPrivateLinkTraffic *string `json:"enforceSecurityGroupInboundRulesOnPrivateLinkTraffic,omitempty"`

	IpAddressType *IpAddressType `json:"ipAddressType,omitempty"`

	IpamPools *IpamPools `json:"ipamPools,omitempty"`

	LoadBalancerArn *string `json:"loadBalancerArn,omitempty"`

	LoadBalancerName *string `json:"loadBalancerName,omitempty"`

	Scheme *LoadBalancerSchemeEnum `json:"scheme,omitempty"`

	SecurityGroups []string `json:"securityGroups,omitempty"`

	State *LoadBalancerState `json:"state,omitempty"`

	Type *LoadBalancerTypeEnum `json:"type,omitempty"`

	VpcId *string `json:"vpcId,omitempty"`
}

// LoadBalancerAddress represents the LoadBalancerAddress structure
type LoadBalancerAddress struct {
	AllocationId *string `json:"allocationId,omitempty"`

	IPv6Address *string `json:"iPv6Address,omitempty"`

	IpAddress *string `json:"ipAddress,omitempty"`

	PrivateIPv4Address *string `json:"privateIPv4Address,omitempty"`
}

// LoadBalancerAddresses represents the LoadBalancerAddresses type
type LoadBalancerAddresses []LoadBalancerAddress

// LoadBalancerArn represents the LoadBalancerArn type
type LoadBalancerArn string

// LoadBalancerArns represents the LoadBalancerArns type
type LoadBalancerArns []string

// LoadBalancerAttribute represents the LoadBalancerAttribute structure
type LoadBalancerAttribute struct {
	Key *string `json:"key,omitempty"`

	Value *string `json:"value,omitempty"`
}

// LoadBalancerAttributeKey represents the LoadBalancerAttributeKey type
type LoadBalancerAttributeKey string

// LoadBalancerAttributeValue represents the LoadBalancerAttributeValue type
type LoadBalancerAttributeValue string

// LoadBalancerAttributes represents the LoadBalancerAttributes type
type LoadBalancerAttributes []LoadBalancerAttribute

// LoadBalancerName represents the LoadBalancerName type
type LoadBalancerName string

// LoadBalancerNames represents the LoadBalancerNames type
type LoadBalancerNames []string

// LoadBalancerNotFoundException represents the LoadBalancerNotFoundException structure
type LoadBalancerNotFoundException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for LoadBalancerNotFoundException
func (e LoadBalancerNotFoundException) Error() string {
	return "LoadBalancerNotFoundException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e LoadBalancerNotFoundException) ErrorCode() string {
	return "LoadBalancerNotFoundException"
}

// ErrorFault indicates whether this is a client or server error
func (e LoadBalancerNotFoundException) ErrorFault() string {
	return "client"
}

// LoadBalancerState represents the LoadBalancerState structure
type LoadBalancerState struct {
	Code *LoadBalancerStateEnum `json:"code,omitempty"`

	Reason *string `json:"reason,omitempty"`
}

// LoadBalancers represents the LoadBalancers type
type LoadBalancers []LoadBalancer

// Location represents the Location type
type Location string

// Marker represents the Marker type
type Marker string

// Matcher represents the Matcher structure
type Matcher struct {
	GrpcCode *string `json:"grpcCode,omitempty"`

	HttpCode *string `json:"httpCode,omitempty"`
}

// Max represents the Max type
type Max string

// MinimumLoadBalancerCapacity represents the MinimumLoadBalancerCapacity structure
type MinimumLoadBalancerCapacity struct {
	CapacityUnits *int32 `json:"capacityUnits,omitempty"`
}

// Mode represents the Mode type
type Mode string

// ModifyCapacityReservationInput represents the ModifyCapacityReservationInput structure
type ModifyCapacityReservationInput struct {
	LoadBalancerArn string `json:"loadBalancerArn"`

	MinimumLoadBalancerCapacity *MinimumLoadBalancerCapacity `json:"minimumLoadBalancerCapacity,omitempty"`

	ResetCapacityReservation *bool `json:"resetCapacityReservation,omitempty"`
}

// ModifyCapacityReservationOutput represents the ModifyCapacityReservationOutput structure
type ModifyCapacityReservationOutput struct {
	CapacityReservationState []ZonalCapacityReservationState `json:"capacityReservationState,omitempty"`

	DecreaseRequestsRemaining *int32 `json:"decreaseRequestsRemaining,omitempty"`

	LastModifiedTime *time.Time `json:"lastModifiedTime,omitempty"`

	MinimumLoadBalancerCapacity *MinimumLoadBalancerCapacity `json:"minimumLoadBalancerCapacity,omitempty"`
}

// ModifyIpPoolsInput represents the ModifyIpPoolsInput structure
type ModifyIpPoolsInput struct {
	IpamPools *IpamPools `json:"ipamPools,omitempty"`

	LoadBalancerArn string `json:"loadBalancerArn"`

	RemoveIpamPools []RemoveIpamPoolEnum `json:"removeIpamPools,omitempty"`
}

// ModifyIpPoolsOutput represents the ModifyIpPoolsOutput structure
type ModifyIpPoolsOutput struct {
	IpamPools *IpamPools `json:"ipamPools,omitempty"`
}

// ModifyListenerAttributesInput represents the ModifyListenerAttributesInput structure
type ModifyListenerAttributesInput struct {
	Attributes []ListenerAttribute `json:"attributes"`

	ListenerArn string `json:"listenerArn"`
}

// ModifyListenerAttributesOutput represents the ModifyListenerAttributesOutput structure
type ModifyListenerAttributesOutput struct {
	Attributes []ListenerAttribute `json:"attributes,omitempty"`
}

// ModifyListenerInput represents the ModifyListenerInput structure
type ModifyListenerInput struct {
	AlpnPolicy []string `json:"alpnPolicy,omitempty"`

	Certificates []Certificate `json:"certificates,omitempty"`

	DefaultActions []Action `json:"defaultActions,omitempty"`

	ListenerArn string `json:"listenerArn"`

	MutualAuthentication *MutualAuthenticationAttributes `json:"mutualAuthentication,omitempty"`

	Port *int32 `json:"port,omitempty"`

	Protocol *ProtocolEnum `json:"protocol,omitempty"`

	SslPolicy *string `json:"sslPolicy,omitempty"`
}

// ModifyListenerOutput represents the ModifyListenerOutput structure
type ModifyListenerOutput struct {
	Listeners []Listener `json:"listeners,omitempty"`
}

// ModifyLoadBalancerAttributesInput represents the ModifyLoadBalancerAttributesInput structure
type ModifyLoadBalancerAttributesInput struct {
	Attributes []LoadBalancerAttribute `json:"attributes"`

	LoadBalancerArn string `json:"loadBalancerArn"`
}

// ModifyLoadBalancerAttributesOutput represents the ModifyLoadBalancerAttributesOutput structure
type ModifyLoadBalancerAttributesOutput struct {
	Attributes []LoadBalancerAttribute `json:"attributes,omitempty"`
}

// ModifyRuleInput represents the ModifyRuleInput structure
type ModifyRuleInput struct {
	Actions []Action `json:"actions,omitempty"`

	Conditions []RuleCondition `json:"conditions,omitempty"`

	RuleArn string `json:"ruleArn"`
}

// ModifyRuleOutput represents the ModifyRuleOutput structure
type ModifyRuleOutput struct {
	Rules []Rule `json:"rules,omitempty"`
}

// ModifyTargetGroupAttributesInput represents the ModifyTargetGroupAttributesInput structure
type ModifyTargetGroupAttributesInput struct {
	Attributes []TargetGroupAttribute `json:"attributes"`

	TargetGroupArn string `json:"targetGroupArn"`
}

// ModifyTargetGroupAttributesOutput represents the ModifyTargetGroupAttributesOutput structure
type ModifyTargetGroupAttributesOutput struct {
	Attributes []TargetGroupAttribute `json:"attributes,omitempty"`
}

// ModifyTargetGroupInput represents the ModifyTargetGroupInput structure
type ModifyTargetGroupInput struct {
	HealthCheckEnabled *bool `json:"healthCheckEnabled,omitempty"`

	HealthCheckIntervalSeconds *int32 `json:"healthCheckIntervalSeconds,omitempty"`

	HealthCheckPath *string `json:"healthCheckPath,omitempty"`

	HealthCheckPort *string `json:"healthCheckPort,omitempty"`

	HealthCheckProtocol *ProtocolEnum `json:"healthCheckProtocol,omitempty"`

	HealthCheckTimeoutSeconds *int32 `json:"healthCheckTimeoutSeconds,omitempty"`

	HealthyThresholdCount *int32 `json:"healthyThresholdCount,omitempty"`

	Matcher *Matcher `json:"matcher,omitempty"`

	TargetGroupArn string `json:"targetGroupArn"`

	UnhealthyThresholdCount *int32 `json:"unhealthyThresholdCount,omitempty"`
}

// ModifyTargetGroupOutput represents the ModifyTargetGroupOutput structure
type ModifyTargetGroupOutput struct {
	TargetGroups []TargetGroup `json:"targetGroups,omitempty"`
}

// ModifyTrustStoreInput represents the ModifyTrustStoreInput structure
type ModifyTrustStoreInput struct {
	CaCertificatesBundleS3Bucket string `json:"caCertificatesBundleS3Bucket"`

	CaCertificatesBundleS3Key string `json:"caCertificatesBundleS3Key"`

	CaCertificatesBundleS3ObjectVersion *string `json:"caCertificatesBundleS3ObjectVersion,omitempty"`

	TrustStoreArn string `json:"trustStoreArn"`
}

// ModifyTrustStoreOutput represents the ModifyTrustStoreOutput structure
type ModifyTrustStoreOutput struct {
	TrustStores []TrustStore `json:"trustStores,omitempty"`
}

// MutualAuthenticationAttributes represents the MutualAuthenticationAttributes structure
type MutualAuthenticationAttributes struct {
	AdvertiseTrustStoreCaNames *AdvertiseTrustStoreCaNamesEnum `json:"advertiseTrustStoreCaNames,omitempty"`

	IgnoreClientCertificateExpiry *bool `json:"ignoreClientCertificateExpiry,omitempty"`

	Mode *string `json:"mode,omitempty"`

	TrustStoreArn *string `json:"trustStoreArn,omitempty"`

	TrustStoreAssociationStatus *TrustStoreAssociationStatusEnum `json:"trustStoreAssociationStatus,omitempty"`
}

// Name represents the Name type
type Name string

// NumberOfCaCertificates represents the NumberOfCaCertificates type
type NumberOfCaCertificates int32

// NumberOfRevokedEntries represents the NumberOfRevokedEntries type
type NumberOfRevokedEntries int64

// OperationNotPermittedException represents the OperationNotPermittedException structure
type OperationNotPermittedException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for OperationNotPermittedException
func (e OperationNotPermittedException) Error() string {
	return "OperationNotPermittedException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e OperationNotPermittedException) ErrorCode() string {
	return "OperationNotPermittedException"
}

// ErrorFault indicates whether this is a client or server error
func (e OperationNotPermittedException) ErrorFault() string {
	return "client"
}

// OutpostId represents the OutpostId type
type OutpostId string

// PageSize represents the PageSize type
type PageSize int32

// Path represents the Path type
type Path string

// PathPatternConditionConfig represents the PathPatternConditionConfig structure
type PathPatternConditionConfig struct {
	Values []string `json:"values,omitempty"`
}

// Policy represents the Policy type
type Policy string

// Port represents the Port type
type Port int32

// PriorRequestNotCompleteException represents the PriorRequestNotCompleteException structure
type PriorRequestNotCompleteException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for PriorRequestNotCompleteException
func (e PriorRequestNotCompleteException) Error() string {
	return "PriorRequestNotCompleteException: AWS client error (HTTP 429)"
}

// ErrorCode returns the AWS error code
func (e PriorRequestNotCompleteException) ErrorCode() string {
	return "PriorRequestNotCompleteException"
}

// ErrorFault indicates whether this is a client or server error
func (e PriorRequestNotCompleteException) ErrorFault() string {
	return "client"
}

// PriorityInUseException represents the PriorityInUseException structure
type PriorityInUseException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for PriorityInUseException
func (e PriorityInUseException) Error() string {
	return "PriorityInUseException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e PriorityInUseException) ErrorCode() string {
	return "PriorityInUseException"
}

// ErrorFault indicates whether this is a client or server error
func (e PriorityInUseException) ErrorFault() string {
	return "client"
}

// PrivateIPv4Address represents the PrivateIPv4Address type
type PrivateIPv4Address string

// ProtocolVersion represents the ProtocolVersion type
type ProtocolVersion string

// QueryStringConditionConfig represents the QueryStringConditionConfig structure
type QueryStringConditionConfig struct {
	Values []QueryStringKeyValuePair `json:"values,omitempty"`
}

// QueryStringKeyValuePair represents the QueryStringKeyValuePair structure
type QueryStringKeyValuePair struct {
	Key *string `json:"key,omitempty"`

	Value *string `json:"value,omitempty"`
}

// QueryStringKeyValuePairList represents the QueryStringKeyValuePairList type
type QueryStringKeyValuePairList []QueryStringKeyValuePair

// RedirectActionConfig represents the RedirectActionConfig structure
type RedirectActionConfig struct {
	Host *string `json:"host,omitempty"`

	Path *string `json:"path,omitempty"`

	Port *string `json:"port,omitempty"`

	Protocol *string `json:"protocol,omitempty"`

	Query *string `json:"query,omitempty"`

	StatusCode RedirectActionStatusCodeEnum `json:"statusCode"`
}

// RedirectActionHost represents the RedirectActionHost type
type RedirectActionHost string

// RedirectActionPath represents the RedirectActionPath type
type RedirectActionPath string

// RedirectActionPort represents the RedirectActionPort type
type RedirectActionPort string

// RedirectActionProtocol represents the RedirectActionProtocol type
type RedirectActionProtocol string

// RedirectActionQuery represents the RedirectActionQuery type
type RedirectActionQuery string

// RegisterTargetsInput represents the RegisterTargetsInput structure
type RegisterTargetsInput struct {
	TargetGroupArn string `json:"targetGroupArn"`

	Targets []TargetDescription `json:"targets"`
}

// RegisterTargetsOutput represents the RegisterTargetsOutput structure
type RegisterTargetsOutput struct {
}

// RemoveIpamPools represents the RemoveIpamPools type
type RemoveIpamPools []RemoveIpamPoolEnum

// RemoveListenerCertificatesInput represents the RemoveListenerCertificatesInput structure
type RemoveListenerCertificatesInput struct {
	Certificates []Certificate `json:"certificates"`

	ListenerArn string `json:"listenerArn"`
}

// RemoveListenerCertificatesOutput represents the RemoveListenerCertificatesOutput structure
type RemoveListenerCertificatesOutput struct {
}

// RemoveTagsInput represents the RemoveTagsInput structure
type RemoveTagsInput struct {
	ResourceArns []string `json:"resourceArns"`

	TagKeys []string `json:"tagKeys"`
}

// RemoveTagsOutput represents the RemoveTagsOutput structure
type RemoveTagsOutput struct {
}

// RemoveTrustStoreRevocationsInput represents the RemoveTrustStoreRevocationsInput structure
type RemoveTrustStoreRevocationsInput struct {
	RevocationIds []int64 `json:"revocationIds"`

	TrustStoreArn string `json:"trustStoreArn"`
}

// RemoveTrustStoreRevocationsOutput represents the RemoveTrustStoreRevocationsOutput structure
type RemoveTrustStoreRevocationsOutput struct {
}

// ResetCapacityReservation represents the ResetCapacityReservation type
type ResetCapacityReservation bool

// ResourceArn represents the ResourceArn type
type ResourceArn string

// ResourceArns represents the ResourceArns type
type ResourceArns []string

// ResourceInUseException represents the ResourceInUseException structure
type ResourceInUseException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for ResourceInUseException
func (e ResourceInUseException) Error() string {
	return "ResourceInUseException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e ResourceInUseException) ErrorCode() string {
	return "ResourceInUseException"
}

// ErrorFault indicates whether this is a client or server error
func (e ResourceInUseException) ErrorFault() string {
	return "client"
}

// ResourceNotFoundException represents the ResourceNotFoundException structure
type ResourceNotFoundException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for ResourceNotFoundException
func (e ResourceNotFoundException) Error() string {
	return "ResourceNotFoundException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e ResourceNotFoundException) ErrorCode() string {
	return "ResourceNotFoundException"
}

// ErrorFault indicates whether this is a client or server error
func (e ResourceNotFoundException) ErrorFault() string {
	return "client"
}

// RevocationContent represents the RevocationContent structure
type RevocationContent struct {
	RevocationType *RevocationType `json:"revocationType,omitempty"`

	S3Bucket *string `json:"s3Bucket,omitempty"`

	S3Key *string `json:"s3Key,omitempty"`

	S3ObjectVersion *string `json:"s3ObjectVersion,omitempty"`
}

// RevocationContentNotFoundException represents the RevocationContentNotFoundException structure
type RevocationContentNotFoundException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for RevocationContentNotFoundException
func (e RevocationContentNotFoundException) Error() string {
	return "RevocationContentNotFoundException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e RevocationContentNotFoundException) ErrorCode() string {
	return "RevocationContentNotFoundException"
}

// ErrorFault indicates whether this is a client or server error
func (e RevocationContentNotFoundException) ErrorFault() string {
	return "client"
}

// RevocationContents represents the RevocationContents type
type RevocationContents []RevocationContent

// RevocationId represents the RevocationId type
type RevocationId int64

// RevocationIdNotFoundException represents the RevocationIdNotFoundException structure
type RevocationIdNotFoundException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for RevocationIdNotFoundException
func (e RevocationIdNotFoundException) Error() string {
	return "RevocationIdNotFoundException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e RevocationIdNotFoundException) ErrorCode() string {
	return "RevocationIdNotFoundException"
}

// ErrorFault indicates whether this is a client or server error
func (e RevocationIdNotFoundException) ErrorFault() string {
	return "client"
}

// RevocationIds represents the RevocationIds type
type RevocationIds []int64

// Rule represents the Rule structure
type Rule struct {
	Actions []Action `json:"actions,omitempty"`

	Conditions []RuleCondition `json:"conditions,omitempty"`

	IsDefault *bool `json:"isDefault,omitempty"`

	Priority *string `json:"priority,omitempty"`

	RuleArn *string `json:"ruleArn,omitempty"`
}

// RuleArn represents the RuleArn type
type RuleArn string

// RuleArns represents the RuleArns type
type RuleArns []string

// RuleCondition represents the RuleCondition structure
type RuleCondition struct {
	Field *string `json:"field,omitempty"`

	HostHeaderConfig *HostHeaderConditionConfig `json:"hostHeaderConfig,omitempty"`

	HttpHeaderConfig *HttpHeaderConditionConfig `json:"httpHeaderConfig,omitempty"`

	HttpRequestMethodConfig *HttpRequestMethodConditionConfig `json:"httpRequestMethodConfig,omitempty"`

	PathPatternConfig *PathPatternConditionConfig `json:"pathPatternConfig,omitempty"`

	QueryStringConfig *QueryStringConditionConfig `json:"queryStringConfig,omitempty"`

	SourceIpConfig *SourceIpConditionConfig `json:"sourceIpConfig,omitempty"`

	Values []string `json:"values,omitempty"`
}

// RuleConditionList represents the RuleConditionList type
type RuleConditionList []RuleCondition

// RuleNotFoundException represents the RuleNotFoundException structure
type RuleNotFoundException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for RuleNotFoundException
func (e RuleNotFoundException) Error() string {
	return "RuleNotFoundException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e RuleNotFoundException) ErrorCode() string {
	return "RuleNotFoundException"
}

// ErrorFault indicates whether this is a client or server error
func (e RuleNotFoundException) ErrorFault() string {
	return "client"
}

// RulePriority represents the RulePriority type
type RulePriority int32

// RulePriorityList represents the RulePriorityList type
type RulePriorityList []RulePriorityPair

// RulePriorityPair represents the RulePriorityPair structure
type RulePriorityPair struct {
	Priority *int32 `json:"priority,omitempty"`

	RuleArn *string `json:"ruleArn,omitempty"`
}

// Rules represents the Rules type
type Rules []Rule

// S3Bucket represents the S3Bucket type
type S3Bucket string

// S3Key represents the S3Key type
type S3Key string

// S3ObjectVersion represents the S3ObjectVersion type
type S3ObjectVersion string

// SSLPolicyNotFoundException represents the SSLPolicyNotFoundException structure
type SSLPolicyNotFoundException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for SSLPolicyNotFoundException
func (e SSLPolicyNotFoundException) Error() string {
	return "SSLPolicyNotFoundException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e SSLPolicyNotFoundException) ErrorCode() string {
	return "SSLPolicyNotFoundException"
}

// ErrorFault indicates whether this is a client or server error
func (e SSLPolicyNotFoundException) ErrorFault() string {
	return "client"
}

// SecurityGroupId represents the SecurityGroupId type
type SecurityGroupId string

// SecurityGroups represents the SecurityGroups type
type SecurityGroups []string

// SetIpAddressTypeInput represents the SetIpAddressTypeInput structure
type SetIpAddressTypeInput struct {
	IpAddressType IpAddressType `json:"ipAddressType"`

	LoadBalancerArn string `json:"loadBalancerArn"`
}

// SetIpAddressTypeOutput represents the SetIpAddressTypeOutput structure
type SetIpAddressTypeOutput struct {
	IpAddressType *IpAddressType `json:"ipAddressType,omitempty"`
}

// SetRulePrioritiesInput represents the SetRulePrioritiesInput structure
type SetRulePrioritiesInput struct {
	RulePriorities []RulePriorityPair `json:"rulePriorities"`
}

// SetRulePrioritiesOutput represents the SetRulePrioritiesOutput structure
type SetRulePrioritiesOutput struct {
	Rules []Rule `json:"rules,omitempty"`
}

// SetSecurityGroupsInput represents the SetSecurityGroupsInput structure
type SetSecurityGroupsInput struct {
	EnforceSecurityGroupInboundRulesOnPrivateLinkTraffic *EnforceSecurityGroupInboundRulesOnPrivateLinkTrafficEnum `json:"enforceSecurityGroupInboundRulesOnPrivateLinkTraffic,omitempty"`

	LoadBalancerArn string `json:"loadBalancerArn"`

	SecurityGroups []string `json:"securityGroups"`
}

// SetSecurityGroupsOutput represents the SetSecurityGroupsOutput structure
type SetSecurityGroupsOutput struct {
	EnforceSecurityGroupInboundRulesOnPrivateLinkTraffic *EnforceSecurityGroupInboundRulesOnPrivateLinkTrafficEnum `json:"enforceSecurityGroupInboundRulesOnPrivateLinkTraffic,omitempty"`

	SecurityGroupIds []string `json:"securityGroupIds,omitempty"`
}

// SetSubnetsInput represents the SetSubnetsInput structure
type SetSubnetsInput struct {
	EnablePrefixForIpv6SourceNat *EnablePrefixForIpv6SourceNatEnum `json:"enablePrefixForIpv6SourceNat,omitempty"`

	IpAddressType *IpAddressType `json:"ipAddressType,omitempty"`

	LoadBalancerArn string `json:"loadBalancerArn"`

	SubnetMappings []SubnetMapping `json:"subnetMappings,omitempty"`

	Subnets []string `json:"subnets,omitempty"`
}

// SetSubnetsOutput represents the SetSubnetsOutput structure
type SetSubnetsOutput struct {
	AvailabilityZones []AvailabilityZone `json:"availabilityZones,omitempty"`

	EnablePrefixForIpv6SourceNat *EnablePrefixForIpv6SourceNatEnum `json:"enablePrefixForIpv6SourceNat,omitempty"`

	IpAddressType *IpAddressType `json:"ipAddressType,omitempty"`
}

// SourceIpConditionConfig represents the SourceIpConditionConfig structure
type SourceIpConditionConfig struct {
	Values []string `json:"values,omitempty"`
}

// SourceNatIpv6Prefix represents the SourceNatIpv6Prefix type
type SourceNatIpv6Prefix string

// SourceNatIpv6Prefixes represents the SourceNatIpv6Prefixes type
type SourceNatIpv6Prefixes []string

// SslPolicies represents the SslPolicies type
type SslPolicies []SslPolicy

// SslPolicy represents the SslPolicy structure
type SslPolicy struct {
	Ciphers []Cipher `json:"ciphers,omitempty"`

	Name *string `json:"name,omitempty"`

	SslProtocols []string `json:"sslProtocols,omitempty"`

	SupportedLoadBalancerTypes []string `json:"supportedLoadBalancerTypes,omitempty"`
}

// SslPolicyName represents the SslPolicyName type
type SslPolicyName string

// SslPolicyNames represents the SslPolicyNames type
type SslPolicyNames []string

// SslProtocol represents the SslProtocol type
type SslProtocol string

// SslProtocols represents the SslProtocols type
type SslProtocols []string

// StateReason represents the StateReason type
type StateReason string

// String represents the String type
type String string

// StringValue represents the StringValue type
type StringValue string

// SubnetId represents the SubnetId type
type SubnetId string

// SubnetMapping represents the SubnetMapping structure
type SubnetMapping struct {
	AllocationId *string `json:"allocationId,omitempty"`

	IPv6Address *string `json:"iPv6Address,omitempty"`

	PrivateIPv4Address *string `json:"privateIPv4Address,omitempty"`

	SourceNatIpv6Prefix *string `json:"sourceNatIpv6Prefix,omitempty"`

	SubnetId *string `json:"subnetId,omitempty"`
}

// SubnetMappings represents the SubnetMappings type
type SubnetMappings []SubnetMapping

// SubnetNotFoundException represents the SubnetNotFoundException structure
type SubnetNotFoundException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for SubnetNotFoundException
func (e SubnetNotFoundException) Error() string {
	return "SubnetNotFoundException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e SubnetNotFoundException) ErrorCode() string {
	return "SubnetNotFoundException"
}

// ErrorFault indicates whether this is a client or server error
func (e SubnetNotFoundException) ErrorFault() string {
	return "client"
}

// Subnets represents the Subnets type
type Subnets []string

// Tag represents the Tag structure
type Tag struct {
	Key string `json:"key"`

	Value *string `json:"value,omitempty"`
}

// TagDescription represents the TagDescription structure
type TagDescription struct {
	ResourceArn *string `json:"resourceArn,omitempty"`

	Tags []Tag `json:"tags,omitempty"`
}

// TagDescriptions represents the TagDescriptions type
type TagDescriptions []TagDescription

// TagKey represents the TagKey type
type TagKey string

// TagKeys represents the TagKeys type
type TagKeys []string

// TagList represents the TagList type
type TagList []Tag

// TagValue represents the TagValue type
type TagValue string

// TargetDescription represents the TargetDescription structure
type TargetDescription struct {
	AvailabilityZone *string `json:"availabilityZone,omitempty"`

	Id string `json:"id"`

	Port *int32 `json:"port,omitempty"`
}

// TargetDescriptions represents the TargetDescriptions type
type TargetDescriptions []TargetDescription

// TargetGroup represents the TargetGroup structure
type TargetGroup struct {
	HealthCheckEnabled *bool `json:"healthCheckEnabled,omitempty"`

	HealthCheckIntervalSeconds *int32 `json:"healthCheckIntervalSeconds,omitempty"`

	HealthCheckPath *string `json:"healthCheckPath,omitempty"`

	HealthCheckPort *string `json:"healthCheckPort,omitempty"`

	HealthCheckProtocol *ProtocolEnum `json:"healthCheckProtocol,omitempty"`

	HealthCheckTimeoutSeconds *int32 `json:"healthCheckTimeoutSeconds,omitempty"`

	HealthyThresholdCount *int32 `json:"healthyThresholdCount,omitempty"`

	IpAddressType *TargetGroupIpAddressTypeEnum `json:"ipAddressType,omitempty"`

	LoadBalancerArns []string `json:"loadBalancerArns,omitempty"`

	Matcher *Matcher `json:"matcher,omitempty"`

	Port *int32 `json:"port,omitempty"`

	Protocol *ProtocolEnum `json:"protocol,omitempty"`

	ProtocolVersion *string `json:"protocolVersion,omitempty"`

	TargetGroupArn *string `json:"targetGroupArn,omitempty"`

	TargetGroupName *string `json:"targetGroupName,omitempty"`

	TargetType *TargetTypeEnum `json:"targetType,omitempty"`

	UnhealthyThresholdCount *int32 `json:"unhealthyThresholdCount,omitempty"`

	VpcId *string `json:"vpcId,omitempty"`
}

// TargetGroupArn represents the TargetGroupArn type
type TargetGroupArn string

// TargetGroupArns represents the TargetGroupArns type
type TargetGroupArns []string

// TargetGroupAssociationLimitException represents the TargetGroupAssociationLimitException structure
type TargetGroupAssociationLimitException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for TargetGroupAssociationLimitException
func (e TargetGroupAssociationLimitException) Error() string {
	return "TargetGroupAssociationLimitException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e TargetGroupAssociationLimitException) ErrorCode() string {
	return "TargetGroupAssociationLimitException"
}

// ErrorFault indicates whether this is a client or server error
func (e TargetGroupAssociationLimitException) ErrorFault() string {
	return "client"
}

// TargetGroupAttribute represents the TargetGroupAttribute structure
type TargetGroupAttribute struct {
	Key *string `json:"key,omitempty"`

	Value *string `json:"value,omitempty"`
}

// TargetGroupAttributeKey represents the TargetGroupAttributeKey type
type TargetGroupAttributeKey string

// TargetGroupAttributeValue represents the TargetGroupAttributeValue type
type TargetGroupAttributeValue string

// TargetGroupAttributes represents the TargetGroupAttributes type
type TargetGroupAttributes []TargetGroupAttribute

// TargetGroupList represents the TargetGroupList type
type TargetGroupList []TargetGroupTuple

// TargetGroupName represents the TargetGroupName type
type TargetGroupName string

// TargetGroupNames represents the TargetGroupNames type
type TargetGroupNames []string

// TargetGroupNotFoundException represents the TargetGroupNotFoundException structure
type TargetGroupNotFoundException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for TargetGroupNotFoundException
func (e TargetGroupNotFoundException) Error() string {
	return "TargetGroupNotFoundException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e TargetGroupNotFoundException) ErrorCode() string {
	return "TargetGroupNotFoundException"
}

// ErrorFault indicates whether this is a client or server error
func (e TargetGroupNotFoundException) ErrorFault() string {
	return "client"
}

// TargetGroupStickinessConfig represents the TargetGroupStickinessConfig structure
type TargetGroupStickinessConfig struct {
	DurationSeconds *int32 `json:"durationSeconds,omitempty"`

	Enabled *bool `json:"enabled,omitempty"`
}

// TargetGroupStickinessDurationSeconds represents the TargetGroupStickinessDurationSeconds type
type TargetGroupStickinessDurationSeconds int32

// TargetGroupStickinessEnabled represents the TargetGroupStickinessEnabled type
type TargetGroupStickinessEnabled bool

// TargetGroupTuple represents the TargetGroupTuple structure
type TargetGroupTuple struct {
	TargetGroupArn *string `json:"targetGroupArn,omitempty"`

	Weight *int32 `json:"weight,omitempty"`
}

// TargetGroupWeight represents the TargetGroupWeight type
type TargetGroupWeight int32

// TargetGroups represents the TargetGroups type
type TargetGroups []TargetGroup

// TargetHealth represents the TargetHealth structure
type TargetHealth struct {
	Description *string `json:"description,omitempty"`

	Reason *TargetHealthReasonEnum `json:"reason,omitempty"`

	State *TargetHealthStateEnum `json:"state,omitempty"`
}

// TargetHealthDescription represents the TargetHealthDescription structure
type TargetHealthDescription struct {
	AdministrativeOverride *AdministrativeOverride `json:"administrativeOverride,omitempty"`

	AnomalyDetection *AnomalyDetection `json:"anomalyDetection,omitempty"`

	HealthCheckPort *string `json:"healthCheckPort,omitempty"`

	Target *TargetDescription `json:"target,omitempty"`

	TargetHealth *TargetHealth `json:"targetHealth,omitempty"`
}

// TargetHealthDescriptions represents the TargetHealthDescriptions type
type TargetHealthDescriptions []TargetHealthDescription

// TargetId represents the TargetId type
type TargetId string

// TooManyActionsException represents the TooManyActionsException structure
type TooManyActionsException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for TooManyActionsException
func (e TooManyActionsException) Error() string {
	return "TooManyActionsException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e TooManyActionsException) ErrorCode() string {
	return "TooManyActionsException"
}

// ErrorFault indicates whether this is a client or server error
func (e TooManyActionsException) ErrorFault() string {
	return "client"
}

// TooManyCertificatesException represents the TooManyCertificatesException structure
type TooManyCertificatesException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for TooManyCertificatesException
func (e TooManyCertificatesException) Error() string {
	return "TooManyCertificatesException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e TooManyCertificatesException) ErrorCode() string {
	return "TooManyCertificatesException"
}

// ErrorFault indicates whether this is a client or server error
func (e TooManyCertificatesException) ErrorFault() string {
	return "client"
}

// TooManyListenersException represents the TooManyListenersException structure
type TooManyListenersException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for TooManyListenersException
func (e TooManyListenersException) Error() string {
	return "TooManyListenersException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e TooManyListenersException) ErrorCode() string {
	return "TooManyListenersException"
}

// ErrorFault indicates whether this is a client or server error
func (e TooManyListenersException) ErrorFault() string {
	return "client"
}

// TooManyLoadBalancersException represents the TooManyLoadBalancersException structure
type TooManyLoadBalancersException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for TooManyLoadBalancersException
func (e TooManyLoadBalancersException) Error() string {
	return "TooManyLoadBalancersException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e TooManyLoadBalancersException) ErrorCode() string {
	return "TooManyLoadBalancersException"
}

// ErrorFault indicates whether this is a client or server error
func (e TooManyLoadBalancersException) ErrorFault() string {
	return "client"
}

// TooManyRegistrationsForTargetIdException represents the TooManyRegistrationsForTargetIdException structure
type TooManyRegistrationsForTargetIdException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for TooManyRegistrationsForTargetIdException
func (e TooManyRegistrationsForTargetIdException) Error() string {
	return "TooManyRegistrationsForTargetIdException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e TooManyRegistrationsForTargetIdException) ErrorCode() string {
	return "TooManyRegistrationsForTargetIdException"
}

// ErrorFault indicates whether this is a client or server error
func (e TooManyRegistrationsForTargetIdException) ErrorFault() string {
	return "client"
}

// TooManyRulesException represents the TooManyRulesException structure
type TooManyRulesException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for TooManyRulesException
func (e TooManyRulesException) Error() string {
	return "TooManyRulesException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e TooManyRulesException) ErrorCode() string {
	return "TooManyRulesException"
}

// ErrorFault indicates whether this is a client or server error
func (e TooManyRulesException) ErrorFault() string {
	return "client"
}

// TooManyTagsException represents the TooManyTagsException structure
type TooManyTagsException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for TooManyTagsException
func (e TooManyTagsException) Error() string {
	return "TooManyTagsException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e TooManyTagsException) ErrorCode() string {
	return "TooManyTagsException"
}

// ErrorFault indicates whether this is a client or server error
func (e TooManyTagsException) ErrorFault() string {
	return "client"
}

// TooManyTargetGroupsException represents the TooManyTargetGroupsException structure
type TooManyTargetGroupsException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for TooManyTargetGroupsException
func (e TooManyTargetGroupsException) Error() string {
	return "TooManyTargetGroupsException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e TooManyTargetGroupsException) ErrorCode() string {
	return "TooManyTargetGroupsException"
}

// ErrorFault indicates whether this is a client or server error
func (e TooManyTargetGroupsException) ErrorFault() string {
	return "client"
}

// TooManyTargetsException represents the TooManyTargetsException structure
type TooManyTargetsException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for TooManyTargetsException
func (e TooManyTargetsException) Error() string {
	return "TooManyTargetsException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e TooManyTargetsException) ErrorCode() string {
	return "TooManyTargetsException"
}

// ErrorFault indicates whether this is a client or server error
func (e TooManyTargetsException) ErrorFault() string {
	return "client"
}

// TooManyTrustStoreRevocationEntriesException represents the TooManyTrustStoreRevocationEntriesException structure
type TooManyTrustStoreRevocationEntriesException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for TooManyTrustStoreRevocationEntriesException
func (e TooManyTrustStoreRevocationEntriesException) Error() string {
	return "TooManyTrustStoreRevocationEntriesException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e TooManyTrustStoreRevocationEntriesException) ErrorCode() string {
	return "TooManyTrustStoreRevocationEntriesException"
}

// ErrorFault indicates whether this is a client or server error
func (e TooManyTrustStoreRevocationEntriesException) ErrorFault() string {
	return "client"
}

// TooManyTrustStoresException represents the TooManyTrustStoresException structure
type TooManyTrustStoresException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for TooManyTrustStoresException
func (e TooManyTrustStoresException) Error() string {
	return "TooManyTrustStoresException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e TooManyTrustStoresException) ErrorCode() string {
	return "TooManyTrustStoresException"
}

// ErrorFault indicates whether this is a client or server error
func (e TooManyTrustStoresException) ErrorFault() string {
	return "client"
}

// TooManyUniqueTargetGroupsPerLoadBalancerException represents the TooManyUniqueTargetGroupsPerLoadBalancerException structure
type TooManyUniqueTargetGroupsPerLoadBalancerException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for TooManyUniqueTargetGroupsPerLoadBalancerException
func (e TooManyUniqueTargetGroupsPerLoadBalancerException) Error() string {
	return "TooManyUniqueTargetGroupsPerLoadBalancerException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e TooManyUniqueTargetGroupsPerLoadBalancerException) ErrorCode() string {
	return "TooManyUniqueTargetGroupsPerLoadBalancerException"
}

// ErrorFault indicates whether this is a client or server error
func (e TooManyUniqueTargetGroupsPerLoadBalancerException) ErrorFault() string {
	return "client"
}

// TotalRevokedEntries represents the TotalRevokedEntries type
type TotalRevokedEntries int64

// TrustStore represents the TrustStore structure
type TrustStore struct {
	Name *string `json:"name,omitempty"`

	NumberOfCaCertificates *int32 `json:"numberOfCaCertificates,omitempty"`

	Status *TrustStoreStatus `json:"status,omitempty"`

	TotalRevokedEntries *int64 `json:"totalRevokedEntries,omitempty"`

	TrustStoreArn *string `json:"trustStoreArn,omitempty"`
}

// TrustStoreArn represents the TrustStoreArn type
type TrustStoreArn string

// TrustStoreArns represents the TrustStoreArns type
type TrustStoreArns []string

// TrustStoreAssociation represents the TrustStoreAssociation structure
type TrustStoreAssociation struct {
	ResourceArn *string `json:"resourceArn,omitempty"`
}

// TrustStoreAssociationNotFoundException represents the TrustStoreAssociationNotFoundException structure
type TrustStoreAssociationNotFoundException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for TrustStoreAssociationNotFoundException
func (e TrustStoreAssociationNotFoundException) Error() string {
	return "TrustStoreAssociationNotFoundException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e TrustStoreAssociationNotFoundException) ErrorCode() string {
	return "TrustStoreAssociationNotFoundException"
}

// ErrorFault indicates whether this is a client or server error
func (e TrustStoreAssociationNotFoundException) ErrorFault() string {
	return "client"
}

// TrustStoreAssociationResourceArn represents the TrustStoreAssociationResourceArn type
type TrustStoreAssociationResourceArn string

// TrustStoreAssociations represents the TrustStoreAssociations type
type TrustStoreAssociations []TrustStoreAssociation

// TrustStoreInUseException represents the TrustStoreInUseException structure
type TrustStoreInUseException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for TrustStoreInUseException
func (e TrustStoreInUseException) Error() string {
	return "TrustStoreInUseException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e TrustStoreInUseException) ErrorCode() string {
	return "TrustStoreInUseException"
}

// ErrorFault indicates whether this is a client or server error
func (e TrustStoreInUseException) ErrorFault() string {
	return "client"
}

// TrustStoreName represents the TrustStoreName type
type TrustStoreName string

// TrustStoreNames represents the TrustStoreNames type
type TrustStoreNames []string

// TrustStoreNotFoundException represents the TrustStoreNotFoundException structure
type TrustStoreNotFoundException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for TrustStoreNotFoundException
func (e TrustStoreNotFoundException) Error() string {
	return "TrustStoreNotFoundException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e TrustStoreNotFoundException) ErrorCode() string {
	return "TrustStoreNotFoundException"
}

// ErrorFault indicates whether this is a client or server error
func (e TrustStoreNotFoundException) ErrorFault() string {
	return "client"
}

// TrustStoreNotReadyException represents the TrustStoreNotReadyException structure
type TrustStoreNotReadyException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for TrustStoreNotReadyException
func (e TrustStoreNotReadyException) Error() string {
	return "TrustStoreNotReadyException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e TrustStoreNotReadyException) ErrorCode() string {
	return "TrustStoreNotReadyException"
}

// ErrorFault indicates whether this is a client or server error
func (e TrustStoreNotReadyException) ErrorFault() string {
	return "client"
}

// TrustStoreRevocation represents the TrustStoreRevocation structure
type TrustStoreRevocation struct {
	NumberOfRevokedEntries *int64 `json:"numberOfRevokedEntries,omitempty"`

	RevocationId *int64 `json:"revocationId,omitempty"`

	RevocationType *RevocationType `json:"revocationType,omitempty"`

	TrustStoreArn *string `json:"trustStoreArn,omitempty"`
}

// TrustStoreRevocations represents the TrustStoreRevocations type
type TrustStoreRevocations []TrustStoreRevocation

// TrustStores represents the TrustStores type
type TrustStores []TrustStore

// UnsupportedProtocolException represents the UnsupportedProtocolException structure
type UnsupportedProtocolException struct {
	Message *string `json:"message,omitempty"`
}

// Error implements the error interface for UnsupportedProtocolException
func (e UnsupportedProtocolException) Error() string {
	return "UnsupportedProtocolException: AWS client error (HTTP 400)"
}

// ErrorCode returns the AWS error code
func (e UnsupportedProtocolException) ErrorCode() string {
	return "UnsupportedProtocolException"
}

// ErrorFault indicates whether this is a client or server error
func (e UnsupportedProtocolException) ErrorFault() string {
	return "client"
}

// VpcId represents the VpcId type
type VpcId string

// ZonalCapacityReservationState represents the ZonalCapacityReservationState structure
type ZonalCapacityReservationState struct {
	AvailabilityZone *string `json:"availabilityZone,omitempty"`

	EffectiveCapacityUnits *float64 `json:"effectiveCapacityUnits,omitempty"`

	State *CapacityReservationStatus `json:"state,omitempty"`
}

// ZonalCapacityReservationStates represents the ZonalCapacityReservationStates type
type ZonalCapacityReservationStates []ZonalCapacityReservationState

// ZoneName represents the ZoneName type
type ZoneName string
