name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    # Skip tests on tag pushes
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    permissions:
      contents: read
      pull-requests: write
      checks: write
      actions: write
    defaults:
      run:
        working-directory: ./controlplane
    env:
      KECS_TEST_MODE: "true"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'controlplane/go.mod'
          cache: true
      - name: Verify dependencies
        run: go mod verify
      - name: Run tests with coverage
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic ./...

      # Install and run Octocov for PR coverage reporting
      - name: Setup Octocov
        if: github.event_name == 'pull_request'
        uses: k1LoW/octocov-action@v1
        with:
          version: latest

      - name: Generate coverage report with Octocov
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OCTOCOV_GITHUB_REF: ${{ github.ref }}
          OCTOCOV_GITHUB_REPOSITORY: ${{ github.repository }}
          OCTOCOV_GITHUB_SHA: ${{ github.sha }}
          OCTOCOV_GITHUB_OWNER: ${{ github.repository_owner }}
          OCTOCOV_GITHUB_REPO: ${{ github.event.repository.name }}
          OCTOCOV_CUSTOM_METRICS_BENCHMARK: ""
        run: |
          cd .. && octocov

      # Run Trivy vulnerability scanner for filesystem
      - name: Run Trivy vulnerability scanner (filesystem)
        uses: aquasecurity/trivy-action@master
        env:
          TRIVY_PLATFORM: 'linux/arm64'  # Match self-hosted runner architecture
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          output: 'trivy-fs-results.txt'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'  # Don't fail the build yet, just report

      - name: Upload Trivy filesystem scan results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-results
          path: trivy-fs-results.txt
          retention-days: 30

  build-and-push:
    name: Build and Push Docker image
    needs: [test]
    runs-on: ubuntu-24.04
    # Run on main branch pushes and tags, not on PRs
    # For tags, test job is skipped so we use always() to ensure this runs
    if: |
      always() && 
      github.event_name == 'push' && 
      (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) &&
      !contains(needs.test.result, 'failure')
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Git describe
        id: git_describe
        run: echo "GIT_DESCRIBE=$(git describe --tags --always)" >> $GITHUB_OUTPUT
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.git_describe.outputs.GIT_DESCRIBE }}
            type=raw,value=latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./controlplane
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ github.ref_name }}

      # Run Trivy vulnerability scanner for Docker image
      - name: Run Trivy vulnerability scanner (Docker image)
        uses: aquasecurity/trivy-action@master
        env:
          TRIVY_PLATFORM: 'linux/arm64'  # Match self-hosted runner architecture
        with:
          image-ref: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.git_describe.outputs.GIT_DESCRIBE }}'
          format: 'table'
          output: 'trivy-docker-results.txt'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'  # Don't fail the build yet, just report

      - name: Upload Trivy Docker scan results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-docker-results
          path: trivy-docker-results.txt
          retention-days: 30

  create-release:
    name: Create GitHub Release
    needs: build-and-push
    runs-on: ubuntu-latest
    # Only run on tag pushes
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: ${{ contains(github.ref_name, '-rc') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-alpha') }}
          generate_release_notes: true
          body: |
            ## Docker Image
            
            ```bash
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ```
            
            ## Installation
            
            ### Homebrew (macOS/Linux)
            ```bash
            brew tap nandemo-ya/kecs
            brew install kecs
            ```
            
            ### Direct Download
            Download the appropriate binary for your platform from the release assets.
            
            ## What's Changed
            
            Auto-generated release notes are below.
