name: GoReleaser

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  # Single job using GoReleaser for all platforms
  goreleaser:
    runs-on: [self-hosted, linux, medium]  # Use self-hosted runner for better performance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      # All builds use CGO_ENABLED=0 since kecs CLI doesn't need DuckDB
      # DuckDB is only needed in the controlplane container, which is built separately
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Token for updating homebrew-kecs repository
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}

      # Note: The separate macOS build job and create-release job are no longer needed
      # GoReleaser handles all platforms and creates the release automatically