name: Web UI CI

on:
  push:
    branches: [ main ]
    paths:
      - 'web-ui/**'
      - '.github/workflows/web-ui-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'web-ui/**'
      - '.github/workflows/web-ui-ci.yml'

jobs:
  test:
    name: Test Web UI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-ui
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: web-ui/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linter
        run: npm run lint --if-present
      
      - name: Run tests
        run: npm test -- --coverage --watchAll=false
        env:
          CI: true
      
      - name: Build
        run: npm run build
      
      - name: Upload test coverage
        if: matrix.node-version == '20.x'
        uses: codecov/codecov-action@v4
        with:
          directory: ./web-ui/coverage
          fail_ci_if_error: false
          flags: web-ui
          name: web-ui-coverage

  build-check:
    name: Build Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-ui
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: web-ui/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Type check
        run: npx tsc --noEmit
      
      - name: Build production bundle
        run: npm run build
        env:
          CI: false  # Treat warnings as warnings, not errors
      
      - name: Check bundle size
        run: |
          echo "Build directory size:"
          du -sh build/
          echo ""
          echo "Largest files in build:"
          find build -type f -exec du -h {} + | sort -rh | head -10
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-ui-build
          path: web-ui/build/
          retention-days: 7