apiVersion: v1
kind: ConfigMap
metadata:
  name: kecs-config
  namespace: kecs-system
  labels:
    app: kecs-controlplane
    kecs.dev/component: "controlplane"
data:
  config.yaml: |
    api:
      port: 8080
      host: 0.0.0.0
    admin:
      port: 8081
      host: 0.0.0.0
    storage:
      type: duckdb
      duckdb:
        path: /data/kecs.db
        memory: false
    kubernetes:
      inCluster: true
      namespace: kecs-system
    features:
      containerMode: false
      traefik: true
      testMode: false
    localstack:
      enabled: true
      services:
        - s3
        - dynamodb
        - sqs
        - sns
        - lambda
      endpoint: http://localstack.kecs-system.svc.cluster.local:4566
    elbv2:
      enabled: true
      dataDir: /data/elbv2