apiVersion: v1
kind: Service
metadata:
  name: kecs-controlplane
  namespace: kecs-system
  labels:
    app: kecs-controlplane
    kecs.dev/component: "controlplane"
spec:
  type: ClusterIP
  selector:
    app: kecs-controlplane
  ports:
  - name: api
    port: 8080
    targetPort: api
    protocol: TCP
  - name: admin
    port: 8081
    targetPort: admin
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kecs-api
  namespace: kecs-system
  labels:
    app: kecs-controlplane
    kecs.dev/component: "controlplane"
    kecs.dev/service: "api"
spec:
  type: ClusterIP
  selector:
    app: kecs-controlplane
  ports:
  - name: http
    port: 80
    targetPort: api
    protocol: TCP