apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kecs-data
  namespace: kecs-system
  labels:
    app: kecs-controlplane
    kecs.dev/component: "controlplane"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path  # k3d default storage class